-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cyt_rdma_cyt_rdma_tx is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    rdma_sq_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
    rdma_sq_TVALID : IN STD_LOGIC;
    rdma_sq_TREADY : OUT STD_LOGIC;
    send_data_TDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    send_data_TVALID : IN STD_LOGIC;
    send_data_TREADY : OUT STD_LOGIC;
    send_data_TKEEP : IN STD_LOGIC_VECTOR (63 downto 0);
    send_data_TSTRB : IN STD_LOGIC_VECTOR (63 downto 0);
    send_data_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    send_data_TDEST : IN STD_LOGIC_VECTOR (7 downto 0);
    tx_TDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    tx_TVALID : OUT STD_LOGIC;
    tx_TREADY : IN STD_LOGIC;
    tx_TKEEP : OUT STD_LOGIC_VECTOR (63 downto 0);
    tx_TSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    tx_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    tx_TDEST : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of cyt_rdma_cyt_rdma_tx is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv64_FFFFFFFFFFFFFFFF : STD_LOGIC_VECTOR (63 downto 0) := "1111111111111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv32_68 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101000";
    constant ap_const_lv32_77 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110111";
    constant ap_const_lv32_78 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_67 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100111";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal txFsmState : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal command_len_V : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal command_vaddr_V : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal command_host_V : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal command_qpn_V : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal command_opcode_V : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal rdma_sq_TDATA_blk_n : STD_LOGIC;
    signal txFsmState_load_load_fu_224_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_nbreadreq_fu_130_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tx_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal txFsmState_load_reg_451 : STD_LOGIC_VECTOR (0 downto 0);
    signal command_len_V_load_reg_455 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_nbreadreq_fu_144_p7 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_463 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_nbwritereq_fu_160_p7 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_467 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tx_word_dest_V_fu_316_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tx_word_dest_V_reg_494 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln186_fu_362_p1 : STD_LOGIC_VECTOR (511 downto 0);
    signal grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_start : STD_LOGIC;
    signal grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_done : STD_LOGIC;
    signal grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_idle : STD_LOGIC;
    signal grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_ready : STD_LOGIC;
    signal grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TREADY : STD_LOGIC;
    signal grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_send_data_TREADY : STD_LOGIC;
    signal grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TDATA : STD_LOGIC_VECTOR (511 downto 0);
    signal grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TVALID : STD_LOGIC;
    signal grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TKEEP : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TSTRB : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TDEST : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tmp_strb_V_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tmp_strb_V_out_ap_vld : STD_LOGIC;
    signal grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_i_1_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_i_1_out_ap_vld : STD_LOGIC;
    signal grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal tmp_strb_V_loc_fu_114 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_1_loc_fu_110 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal regslice_both_tx_V_data_V_U_apdone_blk : STD_LOGIC;
    signal icmp_ln1035_fu_400_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op21_read_state1 : BOOLEAN;
    signal ap_block_state1 : BOOLEAN;
    signal add_ln840_fu_395_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln47_fu_232_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_strb_V_fu_118 : STD_LOGIC_VECTOR (63 downto 0);
    signal empty_fu_122 : STD_LOGIC_VECTOR (63 downto 0);
    signal empty_23_fu_126 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln73_fu_383_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_s_fu_351_p6 : STD_LOGIC_VECTOR (127 downto 0);
    signal icmp_ln1027_fu_373_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln73_fu_378_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln840_fu_391_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal regslice_both_rdma_sq_U_apdone_blk : STD_LOGIC;
    signal rdma_sq_TDATA_int_regslice : STD_LOGIC_VECTOR (127 downto 0);
    signal rdma_sq_TVALID_int_regslice : STD_LOGIC;
    signal rdma_sq_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_rdma_sq_U_ack_in : STD_LOGIC;
    signal regslice_both_send_data_V_data_V_U_apdone_blk : STD_LOGIC;
    signal send_data_TDATA_int_regslice : STD_LOGIC_VECTOR (511 downto 0);
    signal send_data_TVALID_int_regslice : STD_LOGIC;
    signal send_data_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_send_data_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_send_data_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal send_data_TKEEP_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal regslice_both_send_data_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_send_data_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_send_data_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal send_data_TSTRB_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal regslice_both_send_data_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_send_data_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_send_data_V_last_V_U_apdone_blk : STD_LOGIC;
    signal send_data_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_send_data_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_send_data_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_send_data_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal send_data_TDEST_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal regslice_both_send_data_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_send_data_V_dest_V_U_ack_in : STD_LOGIC;
    signal tx_TDATA_int_regslice : STD_LOGIC_VECTOR (511 downto 0);
    signal tx_TVALID_int_regslice : STD_LOGIC;
    signal tx_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_tx_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_tx_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal tx_TKEEP_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal regslice_both_tx_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_tx_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_tx_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal tx_TSTRB_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal regslice_both_tx_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_tx_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_tx_V_last_V_U_apdone_blk : STD_LOGIC;
    signal tx_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_tx_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_tx_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_tx_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal tx_TDEST_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal regslice_both_tx_V_dest_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_tx_V_dest_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component cyt_rdma_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        send_data_TVALID : IN STD_LOGIC;
        tx_TREADY : IN STD_LOGIC;
        send_data_TDATA : IN STD_LOGIC_VECTOR (511 downto 0);
        send_data_TREADY : OUT STD_LOGIC;
        send_data_TKEEP : IN STD_LOGIC_VECTOR (63 downto 0);
        send_data_TSTRB : IN STD_LOGIC_VECTOR (63 downto 0);
        send_data_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        send_data_TDEST : IN STD_LOGIC_VECTOR (7 downto 0);
        tx_word_dest_V : IN STD_LOGIC_VECTOR (7 downto 0);
        tx_TDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
        tx_TVALID : OUT STD_LOGIC;
        tx_TKEEP : OUT STD_LOGIC_VECTOR (63 downto 0);
        tx_TSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
        tx_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        tx_TDEST : OUT STD_LOGIC_VECTOR (7 downto 0);
        tmp_strb_V_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        tmp_strb_V_out_ap_vld : OUT STD_LOGIC;
        i_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        i_1_out_ap_vld : OUT STD_LOGIC );
    end component;


    component cyt_rdma_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197 : component cyt_rdma_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_start,
        ap_done => grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_done,
        ap_idle => grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_idle,
        ap_ready => grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_ready,
        send_data_TVALID => send_data_TVALID_int_regslice,
        tx_TREADY => grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TREADY,
        send_data_TDATA => send_data_TDATA_int_regslice,
        send_data_TREADY => grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_send_data_TREADY,
        send_data_TKEEP => send_data_TKEEP_int_regslice,
        send_data_TSTRB => send_data_TSTRB_int_regslice,
        send_data_TLAST => send_data_TLAST_int_regslice,
        send_data_TDEST => send_data_TDEST_int_regslice,
        tx_word_dest_V => tx_word_dest_V_reg_494,
        tx_TDATA => grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TDATA,
        tx_TVALID => grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TVALID,
        tx_TKEEP => grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TKEEP,
        tx_TSTRB => grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TSTRB,
        tx_TLAST => grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TLAST,
        tx_TDEST => grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TDEST,
        tmp_strb_V_out => grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tmp_strb_V_out,
        tmp_strb_V_out_ap_vld => grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tmp_strb_V_out_ap_vld,
        i_1_out => grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_i_1_out,
        i_1_out_ap_vld => grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_i_1_out_ap_vld);

    regslice_both_rdma_sq_U : component cyt_rdma_regslice_both
    generic map (
        DataWidth => 128)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => rdma_sq_TDATA,
        vld_in => rdma_sq_TVALID,
        ack_in => regslice_both_rdma_sq_U_ack_in,
        data_out => rdma_sq_TDATA_int_regslice,
        vld_out => rdma_sq_TVALID_int_regslice,
        ack_out => rdma_sq_TREADY_int_regslice,
        apdone_blk => regslice_both_rdma_sq_U_apdone_blk);

    regslice_both_send_data_V_data_V_U : component cyt_rdma_regslice_both
    generic map (
        DataWidth => 512)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => send_data_TDATA,
        vld_in => send_data_TVALID,
        ack_in => regslice_both_send_data_V_data_V_U_ack_in,
        data_out => send_data_TDATA_int_regslice,
        vld_out => send_data_TVALID_int_regslice,
        ack_out => send_data_TREADY_int_regslice,
        apdone_blk => regslice_both_send_data_V_data_V_U_apdone_blk);

    regslice_both_send_data_V_keep_V_U : component cyt_rdma_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => send_data_TKEEP,
        vld_in => send_data_TVALID,
        ack_in => regslice_both_send_data_V_keep_V_U_ack_in,
        data_out => send_data_TKEEP_int_regslice,
        vld_out => regslice_both_send_data_V_keep_V_U_vld_out,
        ack_out => send_data_TREADY_int_regslice,
        apdone_blk => regslice_both_send_data_V_keep_V_U_apdone_blk);

    regslice_both_send_data_V_strb_V_U : component cyt_rdma_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => send_data_TSTRB,
        vld_in => send_data_TVALID,
        ack_in => regslice_both_send_data_V_strb_V_U_ack_in,
        data_out => send_data_TSTRB_int_regslice,
        vld_out => regslice_both_send_data_V_strb_V_U_vld_out,
        ack_out => send_data_TREADY_int_regslice,
        apdone_blk => regslice_both_send_data_V_strb_V_U_apdone_blk);

    regslice_both_send_data_V_last_V_U : component cyt_rdma_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => send_data_TLAST,
        vld_in => send_data_TVALID,
        ack_in => regslice_both_send_data_V_last_V_U_ack_in,
        data_out => send_data_TLAST_int_regslice,
        vld_out => regslice_both_send_data_V_last_V_U_vld_out,
        ack_out => send_data_TREADY_int_regslice,
        apdone_blk => regslice_both_send_data_V_last_V_U_apdone_blk);

    regslice_both_send_data_V_dest_V_U : component cyt_rdma_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => send_data_TDEST,
        vld_in => send_data_TVALID,
        ack_in => regslice_both_send_data_V_dest_V_U_ack_in,
        data_out => send_data_TDEST_int_regslice,
        vld_out => regslice_both_send_data_V_dest_V_U_vld_out,
        ack_out => send_data_TREADY_int_regslice,
        apdone_blk => regslice_both_send_data_V_dest_V_U_apdone_blk);

    regslice_both_tx_V_data_V_U : component cyt_rdma_regslice_both
    generic map (
        DataWidth => 512)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => tx_TDATA_int_regslice,
        vld_in => tx_TVALID_int_regslice,
        ack_in => tx_TREADY_int_regslice,
        data_out => tx_TDATA,
        vld_out => regslice_both_tx_V_data_V_U_vld_out,
        ack_out => tx_TREADY,
        apdone_blk => regslice_both_tx_V_data_V_U_apdone_blk);

    regslice_both_tx_V_keep_V_U : component cyt_rdma_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => tx_TKEEP_int_regslice,
        vld_in => tx_TVALID_int_regslice,
        ack_in => regslice_both_tx_V_keep_V_U_ack_in_dummy,
        data_out => tx_TKEEP,
        vld_out => regslice_both_tx_V_keep_V_U_vld_out,
        ack_out => tx_TREADY,
        apdone_blk => regslice_both_tx_V_keep_V_U_apdone_blk);

    regslice_both_tx_V_strb_V_U : component cyt_rdma_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => tx_TSTRB_int_regslice,
        vld_in => tx_TVALID_int_regslice,
        ack_in => regslice_both_tx_V_strb_V_U_ack_in_dummy,
        data_out => tx_TSTRB,
        vld_out => regslice_both_tx_V_strb_V_U_vld_out,
        ack_out => tx_TREADY,
        apdone_blk => regslice_both_tx_V_strb_V_U_apdone_blk);

    regslice_both_tx_V_last_V_U : component cyt_rdma_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => tx_TLAST_int_regslice,
        vld_in => tx_TVALID_int_regslice,
        ack_in => regslice_both_tx_V_last_V_U_ack_in_dummy,
        data_out => tx_TLAST,
        vld_out => regslice_both_tx_V_last_V_U_vld_out,
        ack_out => tx_TREADY,
        apdone_blk => regslice_both_tx_V_last_V_U_apdone_blk);

    regslice_both_tx_V_dest_V_U : component cyt_rdma_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => tx_TDEST_int_regslice,
        vld_in => tx_TVALID_int_regslice,
        ack_in => regslice_both_tx_V_dest_V_U_ack_in_dummy,
        data_out => tx_TDEST,
        vld_out => regslice_both_tx_V_dest_V_U_vld_out,
        ack_out => tx_TREADY,
        apdone_blk => regslice_both_tx_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state7) and (regslice_both_tx_V_data_V_U_apdone_blk = ap_const_logic_0) and ((txFsmState_load_reg_451 = ap_const_lv1_0) or ((tmp_reg_463 = ap_const_lv1_0) or ((tmp_2_reg_467 = ap_const_lv1_0) or (icmp_ln1035_fu_400_p2 = ap_const_lv1_1)))))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_ready = ap_const_logic_1)) then 
                    grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    command_len_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((rdma_sq_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op21_read_state1 = ap_const_boolean_1)))) and (tmp_1_nbreadreq_fu_130_p3 = ap_const_lv1_1) and (txFsmState = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                command_len_V <= rdma_sq_TDATA_int_regslice(95 downto 64);
            elsif (((tmp_2_reg_467 = ap_const_lv1_1) and (tmp_reg_463 = ap_const_lv1_1) and (txFsmState_load_reg_451 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln1035_fu_400_p2 = ap_const_lv1_1) and (regslice_both_tx_V_data_V_U_apdone_blk = ap_const_logic_0))) then 
                command_len_V <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    command_vaddr_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((rdma_sq_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op21_read_state1 = ap_const_boolean_1)))) and (tmp_1_nbreadreq_fu_130_p3 = ap_const_lv1_1) and (txFsmState = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                command_vaddr_V <= trunc_ln47_fu_232_p1;
            elsif (((tmp_2_reg_467 = ap_const_lv1_1) and (tmp_reg_463 = ap_const_lv1_1) and (txFsmState_load_reg_451 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln1035_fu_400_p2 = ap_const_lv1_1) and (regslice_both_tx_V_data_V_U_apdone_blk = ap_const_logic_0))) then 
                command_vaddr_V <= add_ln840_fu_395_p2;
            end if; 
        end if;
    end process;

    empty_23_fu_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_nbwritereq_fu_160_p7 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                empty_23_fu_126 <= command_len_V_load_reg_455;
            elsif (((tmp_2_reg_467 = ap_const_lv1_1) and (tmp_reg_463 = ap_const_lv1_1) and (txFsmState_load_reg_451 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln1035_fu_400_p2 = ap_const_lv1_0) and (regslice_both_tx_V_data_V_U_apdone_blk = ap_const_logic_0))) then 
                empty_23_fu_126 <= select_ln73_fu_383_p3;
            end if; 
        end if;
    end process;

    empty_fu_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_nbwritereq_fu_160_p7 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                empty_fu_122 <= command_vaddr_V;
            elsif (((tmp_2_reg_467 = ap_const_lv1_1) and (tmp_reg_463 = ap_const_lv1_1) and (txFsmState_load_reg_451 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln1035_fu_400_p2 = ap_const_lv1_0) and (regslice_both_tx_V_data_V_U_apdone_blk = ap_const_logic_0))) then 
                empty_fu_122 <= add_ln840_fu_395_p2;
            end if; 
        end if;
    end process;

    txFsmState_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((rdma_sq_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op21_read_state1 = ap_const_boolean_1)))) and (tmp_1_nbreadreq_fu_130_p3 = ap_const_lv1_1) and (txFsmState = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                txFsmState <= ap_const_lv1_1;
            elsif (((tmp_2_reg_467 = ap_const_lv1_1) and (tmp_reg_463 = ap_const_lv1_1) and (txFsmState_load_reg_451 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln1035_fu_400_p2 = ap_const_lv1_1) and (regslice_both_tx_V_data_V_U_apdone_blk = ap_const_logic_0))) then 
                txFsmState <= ap_const_lv1_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((rdma_sq_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op21_read_state1 = ap_const_boolean_1)))) and (tmp_1_nbreadreq_fu_130_p3 = ap_const_lv1_1) and (txFsmState = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                command_host_V <= rdma_sq_TDATA_int_regslice(103 downto 96);
                command_opcode_V <= rdma_sq_TDATA_int_regslice(127 downto 120);
                command_qpn_V <= rdma_sq_TDATA_int_regslice(119 downto 104);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                command_len_V_load_reg_455 <= command_len_V;
                txFsmState_load_reg_451 <= txFsmState;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_i_1_out_ap_vld = ap_const_logic_1))) then
                i_1_loc_fu_110 <= grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_i_1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                tmp_2_reg_467 <= (0=>tx_TREADY_int_regslice, others=>'-');
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((txFsmState_load_load_fu_224_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                tmp_reg_463 <= tmp_nbreadreq_fu_144_p7;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_2_reg_467 = ap_const_lv1_1) and (tmp_reg_463 = ap_const_lv1_1) and (txFsmState_load_reg_451 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln1035_fu_400_p2 = ap_const_lv1_0) and (regslice_both_tx_V_data_V_U_apdone_blk = ap_const_logic_0))) then
                tmp_strb_V_fu_118 <= tmp_strb_V_loc_fu_114;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tmp_strb_V_out_ap_vld = ap_const_logic_1))) then
                tmp_strb_V_loc_fu_114 <= grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tmp_strb_V_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_nbwritereq_fu_160_p7 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                tx_word_dest_V_reg_494 <= tx_word_dest_V_fu_316_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, txFsmState, txFsmState_load_load_fu_224_p1, ap_CS_fsm_state3, ap_CS_fsm_state4, txFsmState_load_reg_451, tmp_nbreadreq_fu_144_p7, tmp_reg_463, grp_nbwritereq_fu_160_p7, tmp_2_reg_467, ap_CS_fsm_state2, grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_done, ap_CS_fsm_state6, ap_CS_fsm_state7, regslice_both_tx_V_data_V_U_apdone_blk, icmp_ln1035_fu_400_p2, ap_predicate_op21_read_state1, rdma_sq_TVALID_int_regslice, tx_TREADY_int_regslice)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((rdma_sq_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op21_read_state1 = ap_const_boolean_1)))) and (tmp_nbreadreq_fu_144_p7 = ap_const_lv1_1) and (txFsmState_load_load_fu_224_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((rdma_sq_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op21_read_state1 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1) and ((tmp_nbreadreq_fu_144_p7 = ap_const_lv1_0) or (txFsmState = ap_const_lv1_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_nbwritereq_fu_160_p7 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state3 => 
                if (((tx_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((tx_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (regslice_both_tx_V_data_V_U_apdone_blk = ap_const_logic_0) and ((txFsmState_load_reg_451 = ap_const_lv1_0) or ((tmp_reg_463 = ap_const_lv1_0) or ((tmp_2_reg_467 = ap_const_lv1_0) or (icmp_ln1035_fu_400_p2 = ap_const_lv1_1)))))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((tmp_2_reg_467 = ap_const_lv1_1) and (tmp_reg_463 = ap_const_lv1_1) and (txFsmState_load_reg_451 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln1035_fu_400_p2 = ap_const_lv1_0) and (regslice_both_tx_V_data_V_U_apdone_blk = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    add_ln840_fu_395_p2 <= std_logic_vector(unsigned(zext_ln840_fu_391_p1) + unsigned(empty_fu_122));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_done_reg, ap_predicate_op21_read_state1, rdma_sq_TVALID_int_regslice)
    begin
        if (((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((rdma_sq_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op21_read_state1 = ap_const_boolean_1)))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(tx_TREADY_int_regslice)
    begin
        if ((tx_TREADY_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(tx_TREADY_int_regslice)
    begin
        if ((tx_TREADY_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_done)
    begin
        if ((grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state7_blk_assign_proc : process(regslice_both_tx_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_tx_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, ap_predicate_op21_read_state1, rdma_sq_TVALID_int_regslice)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((rdma_sq_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op21_read_state1 = ap_const_boolean_1)));
    end process;


    ap_done_assign_proc : process(ap_done_reg, txFsmState_load_reg_451, tmp_reg_463, tmp_2_reg_467, ap_CS_fsm_state7, regslice_both_tx_V_data_V_U_apdone_blk, icmp_ln1035_fu_400_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) and (regslice_both_tx_V_data_V_U_apdone_blk = ap_const_logic_0) and ((txFsmState_load_reg_451 = ap_const_lv1_0) or ((tmp_reg_463 = ap_const_lv1_0) or ((tmp_2_reg_467 = ap_const_lv1_0) or (icmp_ln1035_fu_400_p2 = ap_const_lv1_1)))))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op21_read_state1_assign_proc : process(txFsmState, tmp_1_nbreadreq_fu_130_p3)
    begin
                ap_predicate_op21_read_state1 <= ((tmp_1_nbreadreq_fu_130_p3 = ap_const_lv1_1) and (txFsmState = ap_const_lv1_0));
    end process;


    ap_ready_assign_proc : process(txFsmState_load_reg_451, tmp_reg_463, tmp_2_reg_467, ap_CS_fsm_state7, regslice_both_tx_V_data_V_U_apdone_blk, icmp_ln1035_fu_400_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) and (regslice_both_tx_V_data_V_U_apdone_blk = ap_const_logic_0) and ((txFsmState_load_reg_451 = ap_const_lv1_0) or ((tmp_reg_463 = ap_const_lv1_0) or ((tmp_2_reg_467 = ap_const_lv1_0) or (icmp_ln1035_fu_400_p2 = ap_const_lv1_1)))))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_start <= grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_start_reg;
    grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TREADY <= (tx_TREADY_int_regslice and ap_CS_fsm_state6);
    grp_nbwritereq_fu_160_p7 <= (0=>tx_TREADY_int_regslice, others=>'-');
    icmp_ln1027_fu_373_p2 <= "1" when (unsigned(empty_23_fu_126) < unsigned(i_1_loc_fu_110)) else "0";
    icmp_ln1035_fu_400_p2 <= "1" when (select_ln73_fu_383_p3 = ap_const_lv32_0) else "0";
    p_Result_s_fu_351_p6 <= ((((command_opcode_V & command_qpn_V) & command_host_V) & empty_23_fu_126) & empty_fu_122);

    rdma_sq_TDATA_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, txFsmState, tmp_1_nbreadreq_fu_130_p3, rdma_sq_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (tmp_1_nbreadreq_fu_130_p3 = ap_const_lv1_1) and (txFsmState = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rdma_sq_TDATA_blk_n <= rdma_sq_TVALID_int_regslice;
        else 
            rdma_sq_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    rdma_sq_TREADY <= regslice_both_rdma_sq_U_ack_in;

    rdma_sq_TREADY_int_regslice_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, ap_predicate_op21_read_state1, rdma_sq_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((rdma_sq_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op21_read_state1 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_predicate_op21_read_state1 = ap_const_boolean_1))) then 
            rdma_sq_TREADY_int_regslice <= ap_const_logic_1;
        else 
            rdma_sq_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    select_ln73_fu_383_p3 <= 
        ap_const_lv32_0 when (icmp_ln1027_fu_373_p2(0) = '1') else 
        sub_ln73_fu_378_p2;
    send_data_TREADY <= regslice_both_send_data_V_data_V_U_ack_in;

    send_data_TREADY_int_regslice_assign_proc : process(grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_send_data_TREADY, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            send_data_TREADY_int_regslice <= grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_send_data_TREADY;
        else 
            send_data_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    sub_ln73_fu_378_p2 <= std_logic_vector(unsigned(empty_23_fu_126) - unsigned(i_1_loc_fu_110));
    tmp_1_nbreadreq_fu_130_p3 <= (0=>(rdma_sq_TVALID_int_regslice), others=>'-');
    tmp_nbreadreq_fu_144_p7 <= (0=>(send_data_TVALID_int_regslice), others=>'-');
    trunc_ln47_fu_232_p1 <= rdma_sq_TDATA_int_regslice(64 - 1 downto 0);
    txFsmState_load_load_fu_224_p1 <= txFsmState;

    tx_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4, tx_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            tx_TDATA_blk_n <= tx_TREADY_int_regslice;
        else 
            tx_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    tx_TDATA_int_regslice_assign_proc : process(ap_CS_fsm_state3, zext_ln186_fu_362_p1, grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TDATA, grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TVALID, ap_CS_fsm_state6, tx_TREADY_int_regslice)
    begin
        if (((tx_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            tx_TDATA_int_regslice <= zext_ln186_fu_362_p1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TVALID = ap_const_logic_1))) then 
            tx_TDATA_int_regslice <= grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TDATA;
        else 
            tx_TDATA_int_regslice <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    tx_TDEST_int_regslice_assign_proc : process(ap_CS_fsm_state3, tx_word_dest_V_reg_494, grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TVALID, grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TDEST, ap_CS_fsm_state6, tx_TREADY_int_regslice)
    begin
        if (((tx_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            tx_TDEST_int_regslice <= tx_word_dest_V_reg_494;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TVALID = ap_const_logic_1))) then 
            tx_TDEST_int_regslice <= grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TDEST;
        else 
            tx_TDEST_int_regslice <= "XXXXXXXX";
        end if; 
    end process;


    tx_TKEEP_int_regslice_assign_proc : process(ap_CS_fsm_state3, grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TVALID, grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TKEEP, ap_CS_fsm_state6, tx_TREADY_int_regslice)
    begin
        if (((tx_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            tx_TKEEP_int_regslice <= ap_const_lv64_FFFFFFFFFFFFFFFF;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TVALID = ap_const_logic_1))) then 
            tx_TKEEP_int_regslice <= grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TKEEP;
        else 
            tx_TKEEP_int_regslice <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    tx_TLAST_int_regslice_assign_proc : process(ap_CS_fsm_state3, grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TVALID, grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TLAST, ap_CS_fsm_state6, tx_TREADY_int_regslice)
    begin
        if (((tx_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            tx_TLAST_int_regslice <= ap_const_lv1_0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TVALID = ap_const_logic_1))) then 
            tx_TLAST_int_regslice <= grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TLAST;
        else 
            tx_TLAST_int_regslice <= "X";
        end if; 
    end process;


    tx_TSTRB_int_regslice_assign_proc : process(ap_CS_fsm_state3, grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TVALID, grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TSTRB, ap_CS_fsm_state6, tmp_strb_V_fu_118, tx_TREADY_int_regslice)
    begin
        if (((tx_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            tx_TSTRB_int_regslice <= tmp_strb_V_fu_118;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TVALID = ap_const_logic_1))) then 
            tx_TSTRB_int_regslice <= grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TSTRB;
        else 
            tx_TSTRB_int_regslice <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    tx_TVALID <= regslice_both_tx_V_data_V_U_vld_out;

    tx_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_state3, grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TVALID, ap_CS_fsm_state6, tx_TREADY_int_regslice)
    begin
        if (((tx_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            tx_TVALID_int_regslice <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            tx_TVALID_int_regslice <= grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TVALID;
        else 
            tx_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    tx_word_dest_V_fu_316_p1 <= command_qpn_V(8 - 1 downto 0);
    zext_ln186_fu_362_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_s_fu_351_p6),512));
    zext_ln840_fu_391_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_1_loc_fu_110),64));
end behav;
