-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cyt_rdma_cyt_rdma_rx is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    notif_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    notif_TVALID : OUT STD_LOGIC;
    notif_TREADY : IN STD_LOGIC;
    recv_data_TDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    recv_data_TVALID : OUT STD_LOGIC;
    recv_data_TREADY : IN STD_LOGIC;
    recv_data_TKEEP : OUT STD_LOGIC_VECTOR (63 downto 0);
    recv_data_TSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    recv_data_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    recv_data_TDEST : OUT STD_LOGIC_VECTOR (7 downto 0);
    wr_data_TDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    wr_data_TVALID : OUT STD_LOGIC;
    wr_data_TREADY : IN STD_LOGIC;
    wr_data_TKEEP : OUT STD_LOGIC_VECTOR (63 downto 0);
    wr_data_TSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    wr_data_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    wr_data_TDEST : OUT STD_LOGIC_VECTOR (7 downto 0);
    wr_cmd_TDATA : OUT STD_LOGIC_VECTOR (103 downto 0);
    wr_cmd_TVALID : OUT STD_LOGIC;
    wr_cmd_TREADY : IN STD_LOGIC;
    wr_cmd_TKEEP : OUT STD_LOGIC_VECTOR (12 downto 0);
    wr_cmd_TSTRB : OUT STD_LOGIC_VECTOR (12 downto 0);
    wr_cmd_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    wr_cmd_TDEST : OUT STD_LOGIC_VECTOR (7 downto 0);
    rx_TDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    rx_TVALID : IN STD_LOGIC;
    rx_TREADY : OUT STD_LOGIC;
    rx_TKEEP : IN STD_LOGIC_VECTOR (63 downto 0);
    rx_TSTRB : IN STD_LOGIC_VECTOR (63 downto 0);
    rx_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    rx_TDEST : IN STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of cyt_rdma_cyt_rdma_rx is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_67 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100111";
    constant ap_const_lv32_78 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_1000 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000001000000000000";
    constant ap_const_lv32_56 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010110";
    constant ap_const_lv23_1000 : STD_LOGIC_VECTOR (22 downto 0) := "00000000001000000000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv9_181 : STD_LOGIC_VECTOR (8 downto 0) := "110000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_boolean_0 : BOOLEAN := false;

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal notif_TDATA_blk_n : STD_LOGIC;
    signal tmp_nbreadreq_fu_128_p7 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1019_fu_302_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal wr_cmd_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal rx_TDATA_blk_n : STD_LOGIC;
    signal icmp_ln1019_reg_350 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_ap_start : STD_LOGIC;
    signal grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_ap_done : STD_LOGIC;
    signal grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_ap_idle : STD_LOGIC;
    signal grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_ap_ready : STD_LOGIC;
    signal grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TREADY : STD_LOGIC;
    signal grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_rx_TREADY : STD_LOGIC;
    signal grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TDATA : STD_LOGIC_VECTOR (511 downto 0);
    signal grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TVALID : STD_LOGIC;
    signal grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TKEEP : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TSTRB : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TDEST : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_ap_start : STD_LOGIC;
    signal grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_ap_done : STD_LOGIC;
    signal grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_ap_idle : STD_LOGIC;
    signal grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_ap_ready : STD_LOGIC;
    signal grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TREADY : STD_LOGIC;
    signal grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_rx_TREADY : STD_LOGIC;
    signal grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TDATA : STD_LOGIC_VECTOR (511 downto 0);
    signal grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TVALID : STD_LOGIC;
    signal grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TKEEP : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TSTRB : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TDEST : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_ap_start_reg : STD_LOGIC := '0';
    signal ap_predicate_op32_write_state1 : BOOLEAN;
    signal ap_predicate_op35_write_state1 : BOOLEAN;
    signal ap_block_state1 : BOOLEAN;
    signal ap_block_state1_io : BOOLEAN;
    signal command_len_V_1_fu_247_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln200_fu_278_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln_fu_284_p4 : STD_LOGIC_VECTOR (22 downto 0);
    signal command_opcode_V_1_fu_268_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal current_notif_length_V_fu_294_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal or_ln_fu_308_p5 : STD_LOGIC_VECTOR (54 downto 0);
    signal command_vaddr_V_1_fu_243_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_Result_s_fu_325_p5 : STD_LOGIC_VECTOR (96 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal regslice_both_notif_U_apdone_blk : STD_LOGIC;
    signal regslice_both_recv_data_V_data_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_wr_data_V_data_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_wr_cmd_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state5 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_block_state3_on_subcall_done : BOOLEAN;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal notif_TDATA_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal notif_TVALID_int_regslice : STD_LOGIC;
    signal notif_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_notif_U_vld_out : STD_LOGIC;
    signal recv_data_TVALID_int_regslice : STD_LOGIC;
    signal recv_data_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_recv_data_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_recv_data_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_recv_data_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_recv_data_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_recv_data_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_recv_data_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_recv_data_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_recv_data_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_recv_data_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_recv_data_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_recv_data_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_recv_data_V_dest_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_recv_data_V_dest_V_U_vld_out : STD_LOGIC;
    signal wr_data_TVALID_int_regslice : STD_LOGIC;
    signal wr_data_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_wr_data_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_wr_data_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_wr_data_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_wr_data_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_wr_data_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_wr_data_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_wr_data_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_wr_data_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_wr_data_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_wr_data_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_wr_data_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_wr_data_V_dest_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_wr_data_V_dest_V_U_vld_out : STD_LOGIC;
    signal wr_cmd_TDATA_int_regslice : STD_LOGIC_VECTOR (103 downto 0);
    signal wr_cmd_TVALID_int_regslice : STD_LOGIC;
    signal wr_cmd_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_wr_cmd_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_wr_cmd_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_wr_cmd_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_wr_cmd_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_wr_cmd_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_wr_cmd_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_wr_cmd_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_wr_cmd_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_wr_cmd_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_wr_cmd_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_wr_cmd_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal wr_cmd_TDEST_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal regslice_both_wr_cmd_V_dest_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_wr_cmd_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_rx_V_data_V_U_apdone_blk : STD_LOGIC;
    signal rx_TDATA_int_regslice : STD_LOGIC_VECTOR (511 downto 0);
    signal rx_TVALID_int_regslice : STD_LOGIC;
    signal rx_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_rx_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_rx_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal rx_TKEEP_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal regslice_both_rx_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_rx_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_rx_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal rx_TSTRB_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal regslice_both_rx_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_rx_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_rx_V_last_V_U_apdone_blk : STD_LOGIC;
    signal rx_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_rx_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_rx_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_rx_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal rx_TDEST_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal regslice_both_rx_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_rx_V_dest_V_U_ack_in : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component cyt_rdma_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        rx_TVALID : IN STD_LOGIC;
        recv_data_TREADY : IN STD_LOGIC;
        rx_TDATA : IN STD_LOGIC_VECTOR (511 downto 0);
        rx_TREADY : OUT STD_LOGIC;
        rx_TKEEP : IN STD_LOGIC_VECTOR (63 downto 0);
        rx_TSTRB : IN STD_LOGIC_VECTOR (63 downto 0);
        rx_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        rx_TDEST : IN STD_LOGIC_VECTOR (7 downto 0);
        recv_data_TDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
        recv_data_TVALID : OUT STD_LOGIC;
        recv_data_TKEEP : OUT STD_LOGIC_VECTOR (63 downto 0);
        recv_data_TSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
        recv_data_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        recv_data_TDEST : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component cyt_rdma_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        rx_TVALID : IN STD_LOGIC;
        wr_data_TREADY : IN STD_LOGIC;
        rx_TDATA : IN STD_LOGIC_VECTOR (511 downto 0);
        rx_TREADY : OUT STD_LOGIC;
        rx_TKEEP : IN STD_LOGIC_VECTOR (63 downto 0);
        rx_TSTRB : IN STD_LOGIC_VECTOR (63 downto 0);
        rx_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        rx_TDEST : IN STD_LOGIC_VECTOR (7 downto 0);
        wr_data_TDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
        wr_data_TVALID : OUT STD_LOGIC;
        wr_data_TKEEP : OUT STD_LOGIC_VECTOR (63 downto 0);
        wr_data_TSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
        wr_data_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        wr_data_TDEST : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component cyt_rdma_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187 : component cyt_rdma_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_ap_start,
        ap_done => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_ap_done,
        ap_idle => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_ap_idle,
        ap_ready => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_ap_ready,
        rx_TVALID => rx_TVALID_int_regslice,
        recv_data_TREADY => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TREADY,
        rx_TDATA => rx_TDATA_int_regslice,
        rx_TREADY => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_rx_TREADY,
        rx_TKEEP => rx_TKEEP_int_regslice,
        rx_TSTRB => rx_TSTRB_int_regslice,
        rx_TLAST => rx_TLAST_int_regslice,
        rx_TDEST => rx_TDEST_int_regslice,
        recv_data_TDATA => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TDATA,
        recv_data_TVALID => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TVALID,
        recv_data_TKEEP => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TKEEP,
        recv_data_TSTRB => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TSTRB,
        recv_data_TLAST => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TLAST,
        recv_data_TDEST => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TDEST);

    grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211 : component cyt_rdma_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_ap_start,
        ap_done => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_ap_done,
        ap_idle => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_ap_idle,
        ap_ready => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_ap_ready,
        rx_TVALID => rx_TVALID_int_regslice,
        wr_data_TREADY => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TREADY,
        rx_TDATA => rx_TDATA_int_regslice,
        rx_TREADY => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_rx_TREADY,
        rx_TKEEP => rx_TKEEP_int_regslice,
        rx_TSTRB => rx_TSTRB_int_regslice,
        rx_TLAST => rx_TLAST_int_regslice,
        rx_TDEST => rx_TDEST_int_regslice,
        wr_data_TDATA => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TDATA,
        wr_data_TVALID => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TVALID,
        wr_data_TKEEP => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TKEEP,
        wr_data_TSTRB => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TSTRB,
        wr_data_TLAST => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TLAST,
        wr_data_TDEST => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TDEST);

    regslice_both_notif_U : component cyt_rdma_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => notif_TDATA_int_regslice,
        vld_in => notif_TVALID_int_regslice,
        ack_in => notif_TREADY_int_regslice,
        data_out => notif_TDATA,
        vld_out => regslice_both_notif_U_vld_out,
        ack_out => notif_TREADY,
        apdone_blk => regslice_both_notif_U_apdone_blk);

    regslice_both_recv_data_V_data_V_U : component cyt_rdma_regslice_both
    generic map (
        DataWidth => 512)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TDATA,
        vld_in => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TVALID,
        ack_in => recv_data_TREADY_int_regslice,
        data_out => recv_data_TDATA,
        vld_out => regslice_both_recv_data_V_data_V_U_vld_out,
        ack_out => recv_data_TREADY,
        apdone_blk => regslice_both_recv_data_V_data_V_U_apdone_blk);

    regslice_both_recv_data_V_keep_V_U : component cyt_rdma_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TKEEP,
        vld_in => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TVALID,
        ack_in => regslice_both_recv_data_V_keep_V_U_ack_in_dummy,
        data_out => recv_data_TKEEP,
        vld_out => regslice_both_recv_data_V_keep_V_U_vld_out,
        ack_out => recv_data_TREADY,
        apdone_blk => regslice_both_recv_data_V_keep_V_U_apdone_blk);

    regslice_both_recv_data_V_strb_V_U : component cyt_rdma_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TSTRB,
        vld_in => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TVALID,
        ack_in => regslice_both_recv_data_V_strb_V_U_ack_in_dummy,
        data_out => recv_data_TSTRB,
        vld_out => regslice_both_recv_data_V_strb_V_U_vld_out,
        ack_out => recv_data_TREADY,
        apdone_blk => regslice_both_recv_data_V_strb_V_U_apdone_blk);

    regslice_both_recv_data_V_last_V_U : component cyt_rdma_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TLAST,
        vld_in => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TVALID,
        ack_in => regslice_both_recv_data_V_last_V_U_ack_in_dummy,
        data_out => recv_data_TLAST,
        vld_out => regslice_both_recv_data_V_last_V_U_vld_out,
        ack_out => recv_data_TREADY,
        apdone_blk => regslice_both_recv_data_V_last_V_U_apdone_blk);

    regslice_both_recv_data_V_dest_V_U : component cyt_rdma_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TDEST,
        vld_in => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TVALID,
        ack_in => regslice_both_recv_data_V_dest_V_U_ack_in_dummy,
        data_out => recv_data_TDEST,
        vld_out => regslice_both_recv_data_V_dest_V_U_vld_out,
        ack_out => recv_data_TREADY,
        apdone_blk => regslice_both_recv_data_V_dest_V_U_apdone_blk);

    regslice_both_wr_data_V_data_V_U : component cyt_rdma_regslice_both
    generic map (
        DataWidth => 512)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TDATA,
        vld_in => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TVALID,
        ack_in => wr_data_TREADY_int_regslice,
        data_out => wr_data_TDATA,
        vld_out => regslice_both_wr_data_V_data_V_U_vld_out,
        ack_out => wr_data_TREADY,
        apdone_blk => regslice_both_wr_data_V_data_V_U_apdone_blk);

    regslice_both_wr_data_V_keep_V_U : component cyt_rdma_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TKEEP,
        vld_in => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TVALID,
        ack_in => regslice_both_wr_data_V_keep_V_U_ack_in_dummy,
        data_out => wr_data_TKEEP,
        vld_out => regslice_both_wr_data_V_keep_V_U_vld_out,
        ack_out => wr_data_TREADY,
        apdone_blk => regslice_both_wr_data_V_keep_V_U_apdone_blk);

    regslice_both_wr_data_V_strb_V_U : component cyt_rdma_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TSTRB,
        vld_in => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TVALID,
        ack_in => regslice_both_wr_data_V_strb_V_U_ack_in_dummy,
        data_out => wr_data_TSTRB,
        vld_out => regslice_both_wr_data_V_strb_V_U_vld_out,
        ack_out => wr_data_TREADY,
        apdone_blk => regslice_both_wr_data_V_strb_V_U_apdone_blk);

    regslice_both_wr_data_V_last_V_U : component cyt_rdma_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TLAST,
        vld_in => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TVALID,
        ack_in => regslice_both_wr_data_V_last_V_U_ack_in_dummy,
        data_out => wr_data_TLAST,
        vld_out => regslice_both_wr_data_V_last_V_U_vld_out,
        ack_out => wr_data_TREADY,
        apdone_blk => regslice_both_wr_data_V_last_V_U_apdone_blk);

    regslice_both_wr_data_V_dest_V_U : component cyt_rdma_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TDEST,
        vld_in => grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TVALID,
        ack_in => regslice_both_wr_data_V_dest_V_U_ack_in_dummy,
        data_out => wr_data_TDEST,
        vld_out => regslice_both_wr_data_V_dest_V_U_vld_out,
        ack_out => wr_data_TREADY,
        apdone_blk => regslice_both_wr_data_V_dest_V_U_apdone_blk);

    regslice_both_wr_cmd_V_data_V_U : component cyt_rdma_regslice_both
    generic map (
        DataWidth => 104)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => wr_cmd_TDATA_int_regslice,
        vld_in => wr_cmd_TVALID_int_regslice,
        ack_in => wr_cmd_TREADY_int_regslice,
        data_out => wr_cmd_TDATA,
        vld_out => regslice_both_wr_cmd_V_data_V_U_vld_out,
        ack_out => wr_cmd_TREADY,
        apdone_blk => regslice_both_wr_cmd_V_data_V_U_apdone_blk);

    regslice_both_wr_cmd_V_keep_V_U : component cyt_rdma_regslice_both
    generic map (
        DataWidth => 13)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => ap_const_lv13_0,
        vld_in => wr_cmd_TVALID_int_regslice,
        ack_in => regslice_both_wr_cmd_V_keep_V_U_ack_in_dummy,
        data_out => wr_cmd_TKEEP,
        vld_out => regslice_both_wr_cmd_V_keep_V_U_vld_out,
        ack_out => wr_cmd_TREADY,
        apdone_blk => regslice_both_wr_cmd_V_keep_V_U_apdone_blk);

    regslice_both_wr_cmd_V_strb_V_U : component cyt_rdma_regslice_both
    generic map (
        DataWidth => 13)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => ap_const_lv13_0,
        vld_in => wr_cmd_TVALID_int_regslice,
        ack_in => regslice_both_wr_cmd_V_strb_V_U_ack_in_dummy,
        data_out => wr_cmd_TSTRB,
        vld_out => regslice_both_wr_cmd_V_strb_V_U_vld_out,
        ack_out => wr_cmd_TREADY,
        apdone_blk => regslice_both_wr_cmd_V_strb_V_U_apdone_blk);

    regslice_both_wr_cmd_V_last_V_U : component cyt_rdma_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => ap_const_lv1_1,
        vld_in => wr_cmd_TVALID_int_regslice,
        ack_in => regslice_both_wr_cmd_V_last_V_U_ack_in_dummy,
        data_out => wr_cmd_TLAST,
        vld_out => regslice_both_wr_cmd_V_last_V_U_vld_out,
        ack_out => wr_cmd_TREADY,
        apdone_blk => regslice_both_wr_cmd_V_last_V_U_apdone_blk);

    regslice_both_wr_cmd_V_dest_V_U : component cyt_rdma_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => wr_cmd_TDEST_int_regslice,
        vld_in => wr_cmd_TVALID_int_regslice,
        ack_in => regslice_both_wr_cmd_V_dest_V_U_ack_in_dummy,
        data_out => wr_cmd_TDEST,
        vld_out => regslice_both_wr_cmd_V_dest_V_U_vld_out,
        ack_out => wr_cmd_TREADY,
        apdone_blk => regslice_both_wr_cmd_V_dest_V_U_apdone_blk);

    regslice_both_rx_V_data_V_U : component cyt_rdma_regslice_both
    generic map (
        DataWidth => 512)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => rx_TDATA,
        vld_in => rx_TVALID,
        ack_in => regslice_both_rx_V_data_V_U_ack_in,
        data_out => rx_TDATA_int_regslice,
        vld_out => rx_TVALID_int_regslice,
        ack_out => rx_TREADY_int_regslice,
        apdone_blk => regslice_both_rx_V_data_V_U_apdone_blk);

    regslice_both_rx_V_keep_V_U : component cyt_rdma_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => rx_TKEEP,
        vld_in => rx_TVALID,
        ack_in => regslice_both_rx_V_keep_V_U_ack_in,
        data_out => rx_TKEEP_int_regslice,
        vld_out => regslice_both_rx_V_keep_V_U_vld_out,
        ack_out => rx_TREADY_int_regslice,
        apdone_blk => regslice_both_rx_V_keep_V_U_apdone_blk);

    regslice_both_rx_V_strb_V_U : component cyt_rdma_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => rx_TSTRB,
        vld_in => rx_TVALID,
        ack_in => regslice_both_rx_V_strb_V_U_ack_in,
        data_out => rx_TSTRB_int_regslice,
        vld_out => regslice_both_rx_V_strb_V_U_vld_out,
        ack_out => rx_TREADY_int_regslice,
        apdone_blk => regslice_both_rx_V_strb_V_U_apdone_blk);

    regslice_both_rx_V_last_V_U : component cyt_rdma_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => rx_TLAST,
        vld_in => rx_TVALID,
        ack_in => regslice_both_rx_V_last_V_U_ack_in,
        data_out => rx_TLAST_int_regslice,
        vld_out => regslice_both_rx_V_last_V_U_vld_out,
        ack_out => rx_TREADY_int_regslice,
        apdone_blk => regslice_both_rx_V_last_V_U_apdone_blk);

    regslice_both_rx_V_dest_V_U : component cyt_rdma_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => rx_TDEST,
        vld_in => rx_TVALID,
        ack_in => regslice_both_rx_V_dest_V_U_ack_in,
        data_out => rx_TDEST_int_regslice,
        vld_out => regslice_both_rx_V_dest_V_U_vld_out,
        ack_out => rx_TREADY_int_regslice,
        apdone_blk => regslice_both_rx_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((regslice_both_wr_cmd_V_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_wr_data_V_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_recv_data_V_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_notif_U_apdone_blk = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_ap_start_reg <= ap_const_logic_0;
            else
                if (((wr_cmd_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_ap_ready = ap_const_logic_1)) then 
                    grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_ap_start_reg <= ap_const_logic_0;
            else
                if (((notif_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_ap_ready = ap_const_logic_1)) then 
                    grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_nbreadreq_fu_128_p7 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                icmp_ln1019_reg_350 <= icmp_ln1019_fu_302_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, tmp_nbreadreq_fu_128_p7, icmp_ln1019_fu_302_p2, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state3, ap_predicate_op32_write_state1, ap_predicate_op35_write_state1, ap_block_state1_io, ap_CS_fsm_state5, regslice_both_notif_U_apdone_blk, regslice_both_recv_data_V_data_V_U_apdone_blk, regslice_both_wr_data_V_data_V_U_apdone_blk, regslice_both_wr_cmd_V_data_V_U_apdone_blk, ap_block_state3_on_subcall_done, notif_TREADY_int_regslice, wr_cmd_TREADY_int_regslice, rx_TVALID_int_regslice)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_const_boolean_1 = ap_block_state1_io) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((tmp_nbreadreq_fu_128_p7 = ap_const_lv1_1) and (rx_TVALID_int_regslice = ap_const_logic_0)) or ((wr_cmd_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op35_write_state1 = ap_const_boolean_1)) or ((notif_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op32_write_state1 = ap_const_boolean_1)))) and (icmp_ln1019_fu_302_p2 = ap_const_lv1_1) and (tmp_nbreadreq_fu_128_p7 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                elsif ((not(((ap_const_boolean_1 = ap_block_state1_io) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((tmp_nbreadreq_fu_128_p7 = ap_const_lv1_1) and (rx_TVALID_int_regslice = ap_const_logic_0)) or ((wr_cmd_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op35_write_state1 = ap_const_boolean_1)) or ((notif_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op32_write_state1 = ap_const_boolean_1)))) and (icmp_ln1019_fu_302_p2 = ap_const_lv1_0) and (tmp_nbreadreq_fu_128_p7 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif ((not(((ap_const_boolean_1 = ap_block_state1_io) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((tmp_nbreadreq_fu_128_p7 = ap_const_lv1_1) and (rx_TVALID_int_regslice = ap_const_logic_0)) or ((wr_cmd_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op35_write_state1 = ap_const_boolean_1)) or ((notif_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op32_write_state1 = ap_const_boolean_1)))) and (tmp_nbreadreq_fu_128_p7 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((notif_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_boolean_0 = ap_block_state3_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((wr_cmd_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if ((not(((regslice_both_wr_cmd_V_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_wr_data_V_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_recv_data_V_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_notif_U_apdone_blk = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_done_reg, tmp_nbreadreq_fu_128_p7, ap_predicate_op32_write_state1, ap_predicate_op35_write_state1, ap_block_state1_io, notif_TREADY_int_regslice, wr_cmd_TREADY_int_regslice, rx_TVALID_int_regslice)
    begin
        if (((ap_const_boolean_1 = ap_block_state1_io) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((tmp_nbreadreq_fu_128_p7 = ap_const_lv1_1) and (rx_TVALID_int_regslice = ap_const_logic_0)) or ((wr_cmd_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op35_write_state1 = ap_const_boolean_1)) or ((notif_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op32_write_state1 = ap_const_boolean_1)))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(notif_TREADY_int_regslice)
    begin
        if ((notif_TREADY_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state3_blk_assign_proc : process(ap_block_state3_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state3_on_subcall_done)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(wr_cmd_TREADY_int_regslice)
    begin
        if ((wr_cmd_TREADY_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(regslice_both_notif_U_apdone_blk, regslice_both_recv_data_V_data_V_U_apdone_blk, regslice_both_wr_data_V_data_V_U_apdone_blk, regslice_both_wr_cmd_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_wr_cmd_V_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_wr_data_V_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_recv_data_V_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_notif_U_apdone_blk = ap_const_logic_1))) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, tmp_nbreadreq_fu_128_p7, ap_predicate_op32_write_state1, ap_predicate_op35_write_state1, notif_TREADY_int_regslice, wr_cmd_TREADY_int_regslice, rx_TVALID_int_regslice)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((tmp_nbreadreq_fu_128_p7 = ap_const_lv1_1) and (rx_TVALID_int_regslice = ap_const_logic_0)) or ((wr_cmd_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op35_write_state1 = ap_const_boolean_1)) or ((notif_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op32_write_state1 = ap_const_boolean_1)));
    end process;


    ap_block_state1_io_assign_proc : process(ap_predicate_op32_write_state1, ap_predicate_op35_write_state1, notif_TREADY_int_regslice, wr_cmd_TREADY_int_regslice)
    begin
                ap_block_state1_io <= (((wr_cmd_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op35_write_state1 = ap_const_boolean_1)) or ((notif_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op32_write_state1 = ap_const_boolean_1)));
    end process;


    ap_block_state3_on_subcall_done_assign_proc : process(icmp_ln1019_reg_350, grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_ap_done, grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_ap_done)
    begin
                ap_block_state3_on_subcall_done <= (((icmp_ln1019_reg_350 = ap_const_lv1_1) and (grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_ap_done = ap_const_logic_0)) or ((icmp_ln1019_reg_350 = ap_const_lv1_0) and (grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_ap_done = ap_const_logic_0)));
    end process;


    ap_block_state5_assign_proc : process(regslice_both_notif_U_apdone_blk, regslice_both_recv_data_V_data_V_U_apdone_blk, regslice_both_wr_data_V_data_V_U_apdone_blk, regslice_both_wr_cmd_V_data_V_U_apdone_blk)
    begin
                ap_block_state5 <= ((regslice_both_wr_cmd_V_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_wr_data_V_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_recv_data_V_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_notif_U_apdone_blk = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state5, regslice_both_notif_U_apdone_blk, regslice_both_recv_data_V_data_V_U_apdone_blk, regslice_both_wr_data_V_data_V_U_apdone_blk, regslice_both_wr_cmd_V_data_V_U_apdone_blk)
    begin
        if ((not(((regslice_both_wr_cmd_V_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_wr_data_V_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_recv_data_V_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_notif_U_apdone_blk = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op32_write_state1_assign_proc : process(tmp_nbreadreq_fu_128_p7, icmp_ln1019_fu_302_p2)
    begin
                ap_predicate_op32_write_state1 <= ((icmp_ln1019_fu_302_p2 = ap_const_lv1_0) and (tmp_nbreadreq_fu_128_p7 = ap_const_lv1_1));
    end process;


    ap_predicate_op35_write_state1_assign_proc : process(tmp_nbreadreq_fu_128_p7, icmp_ln1019_fu_302_p2)
    begin
                ap_predicate_op35_write_state1 <= ((icmp_ln1019_fu_302_p2 = ap_const_lv1_1) and (tmp_nbreadreq_fu_128_p7 = ap_const_lv1_1));
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5, regslice_both_notif_U_apdone_blk, regslice_both_recv_data_V_data_V_U_apdone_blk, regslice_both_wr_data_V_data_V_U_apdone_blk, regslice_both_wr_cmd_V_data_V_U_apdone_blk)
    begin
        if ((not(((regslice_both_wr_cmd_V_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_wr_data_V_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_recv_data_V_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_notif_U_apdone_blk = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    command_len_V_1_fu_247_p4 <= rx_TDATA_int_regslice(95 downto 64);
    command_opcode_V_1_fu_268_p4 <= rx_TDATA_int_regslice(127 downto 120);
    command_vaddr_V_1_fu_243_p1 <= rx_TDATA_int_regslice(64 - 1 downto 0);
    current_notif_length_V_fu_294_p3 <= 
        ap_const_lv23_1000 when (icmp_ln200_fu_278_p2(0) = '1') else 
        trunc_ln_fu_284_p4;
    grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_ap_start <= grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_ap_start_reg;
    grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TREADY <= (wr_data_TREADY_int_regslice and ap_CS_fsm_state3);
    grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_ap_start <= grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_ap_start_reg;
    grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TREADY <= (recv_data_TREADY_int_regslice and ap_CS_fsm_state3);
    icmp_ln1019_fu_302_p2 <= "1" when (command_opcode_V_1_fu_268_p4 = ap_const_lv8_1) else "0";
    icmp_ln200_fu_278_p2 <= "1" when (unsigned(command_len_V_1_fu_247_p4) > unsigned(ap_const_lv32_1000)) else "0";

    notif_TDATA_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, tmp_nbreadreq_fu_128_p7, icmp_ln1019_fu_302_p2, ap_CS_fsm_state2, notif_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (icmp_ln1019_fu_302_p2 = ap_const_lv1_0) and (tmp_nbreadreq_fu_128_p7 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            notif_TDATA_blk_n <= notif_TREADY_int_regslice;
        else 
            notif_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    notif_TDATA_int_regslice <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln_fu_308_p5),64));
    notif_TVALID <= regslice_both_notif_U_vld_out;

    notif_TVALID_int_regslice_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, tmp_nbreadreq_fu_128_p7, ap_predicate_op32_write_state1, ap_predicate_op35_write_state1, ap_block_state1_io, notif_TREADY_int_regslice, wr_cmd_TREADY_int_regslice, rx_TVALID_int_regslice)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state1_io) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((tmp_nbreadreq_fu_128_p7 = ap_const_lv1_1) and (rx_TVALID_int_regslice = ap_const_logic_0)) or ((wr_cmd_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op35_write_state1 = ap_const_boolean_1)) or ((notif_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op32_write_state1 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_predicate_op32_write_state1 = ap_const_boolean_1))) then 
            notif_TVALID_int_regslice <= ap_const_logic_1;
        else 
            notif_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    or_ln_fu_308_p5 <= (((current_notif_length_V_fu_294_p3 & ap_const_lv8_0) & rx_TDEST_int_regslice) & ap_const_lv16_0);
    p_Result_s_fu_325_p5 <= (((ap_const_lv1_0 & command_vaddr_V_1_fu_243_p1) & ap_const_lv9_181) & current_notif_length_V_fu_294_p3);
    recv_data_TVALID <= regslice_both_recv_data_V_data_V_U_vld_out;
    recv_data_TVALID_int_regslice <= grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TVALID;

    rx_TDATA_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, tmp_nbreadreq_fu_128_p7, rx_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (tmp_nbreadreq_fu_128_p7 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rx_TDATA_blk_n <= rx_TVALID_int_regslice;
        else 
            rx_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    rx_TREADY <= regslice_both_rx_V_data_V_U_ack_in;

    rx_TREADY_int_regslice_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, tmp_nbreadreq_fu_128_p7, icmp_ln1019_reg_350, grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_rx_TREADY, grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_rx_TREADY, ap_CS_fsm_state3, ap_predicate_op32_write_state1, ap_predicate_op35_write_state1, ap_block_state1_io, notif_TREADY_int_regslice, wr_cmd_TREADY_int_regslice, rx_TVALID_int_regslice)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state1_io) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((tmp_nbreadreq_fu_128_p7 = ap_const_lv1_1) and (rx_TVALID_int_regslice = ap_const_logic_0)) or ((wr_cmd_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op35_write_state1 = ap_const_boolean_1)) or ((notif_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op32_write_state1 = ap_const_boolean_1)))) and (tmp_nbreadreq_fu_128_p7 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rx_TREADY_int_regslice <= ap_const_logic_1;
        elsif (((icmp_ln1019_reg_350 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            rx_TREADY_int_regslice <= grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_rx_TREADY;
        elsif (((icmp_ln1019_reg_350 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            rx_TREADY_int_regslice <= grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_rx_TREADY;
        else 
            rx_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    tmp_nbreadreq_fu_128_p7 <= (0=>(rx_TVALID_int_regslice), others=>'-');
    trunc_ln_fu_284_p4 <= rx_TDATA_int_regslice(86 downto 64);

    wr_cmd_TDATA_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, tmp_nbreadreq_fu_128_p7, icmp_ln1019_fu_302_p2, ap_CS_fsm_state4, wr_cmd_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (icmp_ln1019_fu_302_p2 = ap_const_lv1_1) and (tmp_nbreadreq_fu_128_p7 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            wr_cmd_TDATA_blk_n <= wr_cmd_TREADY_int_regslice;
        else 
            wr_cmd_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    wr_cmd_TDATA_int_regslice <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_s_fu_325_p5),104));
    wr_cmd_TDEST_int_regslice <= rx_TDATA_int_regslice(103 downto 96);
    wr_cmd_TVALID <= regslice_both_wr_cmd_V_data_V_U_vld_out;

    wr_cmd_TVALID_int_regslice_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, tmp_nbreadreq_fu_128_p7, ap_predicate_op32_write_state1, ap_predicate_op35_write_state1, ap_block_state1_io, notif_TREADY_int_regslice, wr_cmd_TREADY_int_regslice, rx_TVALID_int_regslice)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state1_io) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((tmp_nbreadreq_fu_128_p7 = ap_const_lv1_1) and (rx_TVALID_int_regslice = ap_const_logic_0)) or ((wr_cmd_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op35_write_state1 = ap_const_boolean_1)) or ((notif_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op32_write_state1 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_predicate_op35_write_state1 = ap_const_boolean_1))) then 
            wr_cmd_TVALID_int_regslice <= ap_const_logic_1;
        else 
            wr_cmd_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    wr_data_TVALID <= regslice_both_wr_data_V_data_V_U_vld_out;
    wr_data_TVALID_int_regslice <= grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TVALID;
end behav;
