-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cyt_rdma is
port (
    rdma_sq_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
    notif_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    send_data_TDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    send_data_TKEEP : IN STD_LOGIC_VECTOR (63 downto 0);
    send_data_TSTRB : IN STD_LOGIC_VECTOR (63 downto 0);
    send_data_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    send_data_TDEST : IN STD_LOGIC_VECTOR (7 downto 0);
    recv_data_TDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    recv_data_TKEEP : OUT STD_LOGIC_VECTOR (63 downto 0);
    recv_data_TSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    recv_data_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    recv_data_TDEST : OUT STD_LOGIC_VECTOR (7 downto 0);
    wr_data_TDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    wr_data_TKEEP : OUT STD_LOGIC_VECTOR (63 downto 0);
    wr_data_TSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    wr_data_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    wr_data_TDEST : OUT STD_LOGIC_VECTOR (7 downto 0);
    wr_cmd_TDATA : OUT STD_LOGIC_VECTOR (103 downto 0);
    wr_cmd_TKEEP : OUT STD_LOGIC_VECTOR (12 downto 0);
    wr_cmd_TSTRB : OUT STD_LOGIC_VECTOR (12 downto 0);
    wr_cmd_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    wr_cmd_TDEST : OUT STD_LOGIC_VECTOR (7 downto 0);
    wr_sts_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    rx_TDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    rx_TKEEP : IN STD_LOGIC_VECTOR (63 downto 0);
    rx_TSTRB : IN STD_LOGIC_VECTOR (63 downto 0);
    rx_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    rx_TDEST : IN STD_LOGIC_VECTOR (7 downto 0);
    tx_TDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    tx_TKEEP : OUT STD_LOGIC_VECTOR (63 downto 0);
    tx_TSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    tx_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    tx_TDEST : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    rdma_sq_TVALID : IN STD_LOGIC;
    rdma_sq_TREADY : OUT STD_LOGIC;
    send_data_TVALID : IN STD_LOGIC;
    send_data_TREADY : OUT STD_LOGIC;
    tx_TVALID : OUT STD_LOGIC;
    tx_TREADY : IN STD_LOGIC;
    notif_TVALID : OUT STD_LOGIC;
    notif_TREADY : IN STD_LOGIC;
    recv_data_TVALID : OUT STD_LOGIC;
    recv_data_TREADY : IN STD_LOGIC;
    wr_data_TVALID : OUT STD_LOGIC;
    wr_data_TREADY : IN STD_LOGIC;
    wr_cmd_TVALID : OUT STD_LOGIC;
    wr_cmd_TREADY : IN STD_LOGIC;
    rx_TVALID : IN STD_LOGIC;
    rx_TREADY : OUT STD_LOGIC;
    wr_sts_TVALID : IN STD_LOGIC;
    wr_sts_TREADY : OUT STD_LOGIC );
end;


architecture behav of cyt_rdma is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "cyt_rdma_cyt_rdma,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu280-fsvh2892-2L-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=2.353000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=486,HLS_SYN_LUT=756,HLS_VERSION=2022_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal ap_rst_n_inv : STD_LOGIC;
    signal cyt_rdma_tx_U0_ap_start : STD_LOGIC;
    signal cyt_rdma_tx_U0_ap_done : STD_LOGIC;
    signal cyt_rdma_tx_U0_ap_continue : STD_LOGIC;
    signal cyt_rdma_tx_U0_ap_idle : STD_LOGIC;
    signal cyt_rdma_tx_U0_ap_ready : STD_LOGIC;
    signal cyt_rdma_tx_U0_rdma_sq_TREADY : STD_LOGIC;
    signal cyt_rdma_tx_U0_send_data_TREADY : STD_LOGIC;
    signal cyt_rdma_tx_U0_tx_TDATA : STD_LOGIC_VECTOR (511 downto 0);
    signal cyt_rdma_tx_U0_tx_TVALID : STD_LOGIC;
    signal cyt_rdma_tx_U0_tx_TKEEP : STD_LOGIC_VECTOR (63 downto 0);
    signal cyt_rdma_tx_U0_tx_TSTRB : STD_LOGIC_VECTOR (63 downto 0);
    signal cyt_rdma_tx_U0_tx_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal cyt_rdma_tx_U0_tx_TDEST : STD_LOGIC_VECTOR (7 downto 0);
    signal cyt_rdma_rx_U0_ap_start : STD_LOGIC;
    signal cyt_rdma_rx_U0_ap_done : STD_LOGIC;
    signal cyt_rdma_rx_U0_ap_continue : STD_LOGIC;
    signal cyt_rdma_rx_U0_ap_idle : STD_LOGIC;
    signal cyt_rdma_rx_U0_ap_ready : STD_LOGIC;
    signal cyt_rdma_rx_U0_notif_TDATA : STD_LOGIC_VECTOR (63 downto 0);
    signal cyt_rdma_rx_U0_notif_TVALID : STD_LOGIC;
    signal cyt_rdma_rx_U0_recv_data_TDATA : STD_LOGIC_VECTOR (511 downto 0);
    signal cyt_rdma_rx_U0_recv_data_TVALID : STD_LOGIC;
    signal cyt_rdma_rx_U0_recv_data_TKEEP : STD_LOGIC_VECTOR (63 downto 0);
    signal cyt_rdma_rx_U0_recv_data_TSTRB : STD_LOGIC_VECTOR (63 downto 0);
    signal cyt_rdma_rx_U0_recv_data_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal cyt_rdma_rx_U0_recv_data_TDEST : STD_LOGIC_VECTOR (7 downto 0);
    signal cyt_rdma_rx_U0_wr_data_TDATA : STD_LOGIC_VECTOR (511 downto 0);
    signal cyt_rdma_rx_U0_wr_data_TVALID : STD_LOGIC;
    signal cyt_rdma_rx_U0_wr_data_TKEEP : STD_LOGIC_VECTOR (63 downto 0);
    signal cyt_rdma_rx_U0_wr_data_TSTRB : STD_LOGIC_VECTOR (63 downto 0);
    signal cyt_rdma_rx_U0_wr_data_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal cyt_rdma_rx_U0_wr_data_TDEST : STD_LOGIC_VECTOR (7 downto 0);
    signal cyt_rdma_rx_U0_wr_cmd_TDATA : STD_LOGIC_VECTOR (103 downto 0);
    signal cyt_rdma_rx_U0_wr_cmd_TVALID : STD_LOGIC;
    signal cyt_rdma_rx_U0_wr_cmd_TKEEP : STD_LOGIC_VECTOR (12 downto 0);
    signal cyt_rdma_rx_U0_wr_cmd_TSTRB : STD_LOGIC_VECTOR (12 downto 0);
    signal cyt_rdma_rx_U0_wr_cmd_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal cyt_rdma_rx_U0_wr_cmd_TDEST : STD_LOGIC_VECTOR (7 downto 0);
    signal cyt_rdma_rx_U0_rx_TREADY : STD_LOGIC;
    signal cyt_rdma_wr_sts_U0_ap_start : STD_LOGIC;
    signal cyt_rdma_wr_sts_U0_ap_done : STD_LOGIC;
    signal cyt_rdma_wr_sts_U0_ap_continue : STD_LOGIC;
    signal cyt_rdma_wr_sts_U0_ap_idle : STD_LOGIC;
    signal cyt_rdma_wr_sts_U0_ap_ready : STD_LOGIC;
    signal cyt_rdma_wr_sts_U0_wr_sts_TREADY : STD_LOGIC;

    component cyt_rdma_cyt_rdma_tx IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        rdma_sq_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
        rdma_sq_TVALID : IN STD_LOGIC;
        rdma_sq_TREADY : OUT STD_LOGIC;
        send_data_TDATA : IN STD_LOGIC_VECTOR (511 downto 0);
        send_data_TVALID : IN STD_LOGIC;
        send_data_TREADY : OUT STD_LOGIC;
        send_data_TKEEP : IN STD_LOGIC_VECTOR (63 downto 0);
        send_data_TSTRB : IN STD_LOGIC_VECTOR (63 downto 0);
        send_data_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        send_data_TDEST : IN STD_LOGIC_VECTOR (7 downto 0);
        tx_TDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
        tx_TVALID : OUT STD_LOGIC;
        tx_TREADY : IN STD_LOGIC;
        tx_TKEEP : OUT STD_LOGIC_VECTOR (63 downto 0);
        tx_TSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
        tx_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        tx_TDEST : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component cyt_rdma_cyt_rdma_rx IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        notif_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
        notif_TVALID : OUT STD_LOGIC;
        notif_TREADY : IN STD_LOGIC;
        recv_data_TDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
        recv_data_TVALID : OUT STD_LOGIC;
        recv_data_TREADY : IN STD_LOGIC;
        recv_data_TKEEP : OUT STD_LOGIC_VECTOR (63 downto 0);
        recv_data_TSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
        recv_data_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        recv_data_TDEST : OUT STD_LOGIC_VECTOR (7 downto 0);
        wr_data_TDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
        wr_data_TVALID : OUT STD_LOGIC;
        wr_data_TREADY : IN STD_LOGIC;
        wr_data_TKEEP : OUT STD_LOGIC_VECTOR (63 downto 0);
        wr_data_TSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
        wr_data_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        wr_data_TDEST : OUT STD_LOGIC_VECTOR (7 downto 0);
        wr_cmd_TDATA : OUT STD_LOGIC_VECTOR (103 downto 0);
        wr_cmd_TVALID : OUT STD_LOGIC;
        wr_cmd_TREADY : IN STD_LOGIC;
        wr_cmd_TKEEP : OUT STD_LOGIC_VECTOR (12 downto 0);
        wr_cmd_TSTRB : OUT STD_LOGIC_VECTOR (12 downto 0);
        wr_cmd_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        wr_cmd_TDEST : OUT STD_LOGIC_VECTOR (7 downto 0);
        rx_TDATA : IN STD_LOGIC_VECTOR (511 downto 0);
        rx_TVALID : IN STD_LOGIC;
        rx_TREADY : OUT STD_LOGIC;
        rx_TKEEP : IN STD_LOGIC_VECTOR (63 downto 0);
        rx_TSTRB : IN STD_LOGIC_VECTOR (63 downto 0);
        rx_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        rx_TDEST : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component cyt_rdma_cyt_rdma_wr_sts IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        wr_sts_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        wr_sts_TVALID : IN STD_LOGIC;
        wr_sts_TREADY : OUT STD_LOGIC );
    end component;



begin
    cyt_rdma_tx_U0 : component cyt_rdma_cyt_rdma_tx
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => cyt_rdma_tx_U0_ap_start,
        ap_done => cyt_rdma_tx_U0_ap_done,
        ap_continue => cyt_rdma_tx_U0_ap_continue,
        ap_idle => cyt_rdma_tx_U0_ap_idle,
        ap_ready => cyt_rdma_tx_U0_ap_ready,
        rdma_sq_TDATA => rdma_sq_TDATA,
        rdma_sq_TVALID => rdma_sq_TVALID,
        rdma_sq_TREADY => cyt_rdma_tx_U0_rdma_sq_TREADY,
        send_data_TDATA => send_data_TDATA,
        send_data_TVALID => send_data_TVALID,
        send_data_TREADY => cyt_rdma_tx_U0_send_data_TREADY,
        send_data_TKEEP => send_data_TKEEP,
        send_data_TSTRB => send_data_TSTRB,
        send_data_TLAST => send_data_TLAST,
        send_data_TDEST => send_data_TDEST,
        tx_TDATA => cyt_rdma_tx_U0_tx_TDATA,
        tx_TVALID => cyt_rdma_tx_U0_tx_TVALID,
        tx_TREADY => tx_TREADY,
        tx_TKEEP => cyt_rdma_tx_U0_tx_TKEEP,
        tx_TSTRB => cyt_rdma_tx_U0_tx_TSTRB,
        tx_TLAST => cyt_rdma_tx_U0_tx_TLAST,
        tx_TDEST => cyt_rdma_tx_U0_tx_TDEST);

    cyt_rdma_rx_U0 : component cyt_rdma_cyt_rdma_rx
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => cyt_rdma_rx_U0_ap_start,
        ap_done => cyt_rdma_rx_U0_ap_done,
        ap_continue => cyt_rdma_rx_U0_ap_continue,
        ap_idle => cyt_rdma_rx_U0_ap_idle,
        ap_ready => cyt_rdma_rx_U0_ap_ready,
        notif_TDATA => cyt_rdma_rx_U0_notif_TDATA,
        notif_TVALID => cyt_rdma_rx_U0_notif_TVALID,
        notif_TREADY => notif_TREADY,
        recv_data_TDATA => cyt_rdma_rx_U0_recv_data_TDATA,
        recv_data_TVALID => cyt_rdma_rx_U0_recv_data_TVALID,
        recv_data_TREADY => recv_data_TREADY,
        recv_data_TKEEP => cyt_rdma_rx_U0_recv_data_TKEEP,
        recv_data_TSTRB => cyt_rdma_rx_U0_recv_data_TSTRB,
        recv_data_TLAST => cyt_rdma_rx_U0_recv_data_TLAST,
        recv_data_TDEST => cyt_rdma_rx_U0_recv_data_TDEST,
        wr_data_TDATA => cyt_rdma_rx_U0_wr_data_TDATA,
        wr_data_TVALID => cyt_rdma_rx_U0_wr_data_TVALID,
        wr_data_TREADY => wr_data_TREADY,
        wr_data_TKEEP => cyt_rdma_rx_U0_wr_data_TKEEP,
        wr_data_TSTRB => cyt_rdma_rx_U0_wr_data_TSTRB,
        wr_data_TLAST => cyt_rdma_rx_U0_wr_data_TLAST,
        wr_data_TDEST => cyt_rdma_rx_U0_wr_data_TDEST,
        wr_cmd_TDATA => cyt_rdma_rx_U0_wr_cmd_TDATA,
        wr_cmd_TVALID => cyt_rdma_rx_U0_wr_cmd_TVALID,
        wr_cmd_TREADY => wr_cmd_TREADY,
        wr_cmd_TKEEP => cyt_rdma_rx_U0_wr_cmd_TKEEP,
        wr_cmd_TSTRB => cyt_rdma_rx_U0_wr_cmd_TSTRB,
        wr_cmd_TLAST => cyt_rdma_rx_U0_wr_cmd_TLAST,
        wr_cmd_TDEST => cyt_rdma_rx_U0_wr_cmd_TDEST,
        rx_TDATA => rx_TDATA,
        rx_TVALID => rx_TVALID,
        rx_TREADY => cyt_rdma_rx_U0_rx_TREADY,
        rx_TKEEP => rx_TKEEP,
        rx_TSTRB => rx_TSTRB,
        rx_TLAST => rx_TLAST,
        rx_TDEST => rx_TDEST);

    cyt_rdma_wr_sts_U0 : component cyt_rdma_cyt_rdma_wr_sts
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => cyt_rdma_wr_sts_U0_ap_start,
        ap_done => cyt_rdma_wr_sts_U0_ap_done,
        ap_continue => cyt_rdma_wr_sts_U0_ap_continue,
        ap_idle => cyt_rdma_wr_sts_U0_ap_idle,
        ap_ready => cyt_rdma_wr_sts_U0_ap_ready,
        wr_sts_TDATA => wr_sts_TDATA,
        wr_sts_TVALID => wr_sts_TVALID,
        wr_sts_TREADY => cyt_rdma_wr_sts_U0_wr_sts_TREADY);





    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    cyt_rdma_rx_U0_ap_continue <= ap_const_logic_1;
    cyt_rdma_rx_U0_ap_start <= ap_const_logic_1;
    cyt_rdma_tx_U0_ap_continue <= ap_const_logic_1;
    cyt_rdma_tx_U0_ap_start <= ap_const_logic_1;
    cyt_rdma_wr_sts_U0_ap_continue <= ap_const_logic_1;
    cyt_rdma_wr_sts_U0_ap_start <= ap_const_logic_1;
    notif_TDATA <= cyt_rdma_rx_U0_notif_TDATA;
    notif_TVALID <= cyt_rdma_rx_U0_notif_TVALID;
    rdma_sq_TREADY <= cyt_rdma_tx_U0_rdma_sq_TREADY;
    recv_data_TDATA <= cyt_rdma_rx_U0_recv_data_TDATA;
    recv_data_TDEST <= cyt_rdma_rx_U0_recv_data_TDEST;
    recv_data_TKEEP <= cyt_rdma_rx_U0_recv_data_TKEEP;
    recv_data_TLAST <= cyt_rdma_rx_U0_recv_data_TLAST;
    recv_data_TSTRB <= cyt_rdma_rx_U0_recv_data_TSTRB;
    recv_data_TVALID <= cyt_rdma_rx_U0_recv_data_TVALID;
    rx_TREADY <= cyt_rdma_rx_U0_rx_TREADY;
    send_data_TREADY <= cyt_rdma_tx_U0_send_data_TREADY;
    tx_TDATA <= cyt_rdma_tx_U0_tx_TDATA;
    tx_TDEST <= cyt_rdma_tx_U0_tx_TDEST;
    tx_TKEEP <= cyt_rdma_tx_U0_tx_TKEEP;
    tx_TLAST <= cyt_rdma_tx_U0_tx_TLAST;
    tx_TSTRB <= cyt_rdma_tx_U0_tx_TSTRB;
    tx_TVALID <= cyt_rdma_tx_U0_tx_TVALID;
    wr_cmd_TDATA <= cyt_rdma_rx_U0_wr_cmd_TDATA;
    wr_cmd_TDEST <= cyt_rdma_rx_U0_wr_cmd_TDEST;
    wr_cmd_TKEEP <= cyt_rdma_rx_U0_wr_cmd_TKEEP;
    wr_cmd_TLAST <= cyt_rdma_rx_U0_wr_cmd_TLAST;
    wr_cmd_TSTRB <= cyt_rdma_rx_U0_wr_cmd_TSTRB;
    wr_cmd_TVALID <= cyt_rdma_rx_U0_wr_cmd_TVALID;
    wr_data_TDATA <= cyt_rdma_rx_U0_wr_data_TDATA;
    wr_data_TDEST <= cyt_rdma_rx_U0_wr_data_TDEST;
    wr_data_TKEEP <= cyt_rdma_rx_U0_wr_data_TKEEP;
    wr_data_TLAST <= cyt_rdma_rx_U0_wr_data_TLAST;
    wr_data_TSTRB <= cyt_rdma_rx_U0_wr_data_TSTRB;
    wr_data_TVALID <= cyt_rdma_rx_U0_wr_data_TVALID;
    wr_sts_TREADY <= cyt_rdma_wr_sts_U0_wr_sts_TREADY;
end behav;
