// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module cyt_rdma_cyt_rdma_rx (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        notif_TDATA,
        notif_TVALID,
        notif_TREADY,
        recv_data_TDATA,
        recv_data_TVALID,
        recv_data_TREADY,
        recv_data_TKEEP,
        recv_data_TSTRB,
        recv_data_TLAST,
        recv_data_TDEST,
        wr_data_TDATA,
        wr_data_TVALID,
        wr_data_TREADY,
        wr_data_TKEEP,
        wr_data_TSTRB,
        wr_data_TLAST,
        wr_data_TDEST,
        wr_cmd_TDATA,
        wr_cmd_TVALID,
        wr_cmd_TREADY,
        wr_cmd_TKEEP,
        wr_cmd_TSTRB,
        wr_cmd_TLAST,
        wr_cmd_TDEST,
        rx_TDATA,
        rx_TVALID,
        rx_TREADY,
        rx_TKEEP,
        rx_TSTRB,
        rx_TLAST,
        rx_TDEST
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [63:0] notif_TDATA;
output   notif_TVALID;
input   notif_TREADY;
output  [511:0] recv_data_TDATA;
output   recv_data_TVALID;
input   recv_data_TREADY;
output  [63:0] recv_data_TKEEP;
output  [63:0] recv_data_TSTRB;
output  [0:0] recv_data_TLAST;
output  [7:0] recv_data_TDEST;
output  [511:0] wr_data_TDATA;
output   wr_data_TVALID;
input   wr_data_TREADY;
output  [63:0] wr_data_TKEEP;
output  [63:0] wr_data_TSTRB;
output  [0:0] wr_data_TLAST;
output  [7:0] wr_data_TDEST;
output  [103:0] wr_cmd_TDATA;
output   wr_cmd_TVALID;
input   wr_cmd_TREADY;
output  [12:0] wr_cmd_TKEEP;
output  [12:0] wr_cmd_TSTRB;
output  [0:0] wr_cmd_TLAST;
output  [7:0] wr_cmd_TDEST;
input  [511:0] rx_TDATA;
input   rx_TVALID;
output   rx_TREADY;
input  [63:0] rx_TKEEP;
input  [63:0] rx_TSTRB;
input  [0:0] rx_TLAST;
input  [7:0] rx_TDEST;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    notif_TDATA_blk_n;
wire   [0:0] tmp_nbreadreq_fu_128_p7;
wire   [0:0] icmp_ln1019_fu_302_p2;
wire    ap_CS_fsm_state2;
reg    wr_cmd_TDATA_blk_n;
wire    ap_CS_fsm_state4;
reg    rx_TDATA_blk_n;
reg   [0:0] icmp_ln1019_reg_350;
wire    grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_ap_start;
wire    grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_ap_done;
wire    grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_ap_idle;
wire    grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_ap_ready;
wire    grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TREADY;
wire    grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_rx_TREADY;
wire   [511:0] grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TDATA;
wire    grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TVALID;
wire   [63:0] grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TKEEP;
wire   [63:0] grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TSTRB;
wire   [0:0] grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TLAST;
wire   [7:0] grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TDEST;
wire    grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_ap_start;
wire    grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_ap_done;
wire    grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_ap_idle;
wire    grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_ap_ready;
wire    grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TREADY;
wire    grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_rx_TREADY;
wire   [511:0] grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TDATA;
wire    grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TVALID;
wire   [63:0] grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TKEEP;
wire   [63:0] grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TSTRB;
wire   [0:0] grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TLAST;
wire   [7:0] grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TDEST;
reg    grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_ap_start_reg;
wire    ap_CS_fsm_state3;
reg    grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_ap_start_reg;
reg    ap_predicate_op32_write_state1;
reg    ap_predicate_op35_write_state1;
reg    ap_block_state1;
reg    ap_block_state1_io;
wire   [31:0] command_len_V_1_fu_247_p4;
wire   [0:0] icmp_ln200_fu_278_p2;
wire   [22:0] trunc_ln_fu_284_p4;
wire   [7:0] command_opcode_V_1_fu_268_p4;
wire   [22:0] current_notif_length_V_fu_294_p3;
wire   [54:0] or_ln_fu_308_p5;
wire   [63:0] command_vaddr_V_1_fu_243_p1;
wire   [96:0] p_Result_s_fu_325_p5;
wire    ap_CS_fsm_state5;
wire    regslice_both_notif_U_apdone_blk;
wire    regslice_both_recv_data_V_data_V_U_apdone_blk;
wire    regslice_both_wr_data_V_data_V_U_apdone_blk;
wire    regslice_both_wr_cmd_V_data_V_U_apdone_blk;
reg    ap_block_state5;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_block_state3_on_subcall_done;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire   [63:0] notif_TDATA_int_regslice;
reg    notif_TVALID_int_regslice;
wire    notif_TREADY_int_regslice;
wire    regslice_both_notif_U_vld_out;
wire    recv_data_TVALID_int_regslice;
wire    recv_data_TREADY_int_regslice;
wire    regslice_both_recv_data_V_data_V_U_vld_out;
wire    regslice_both_recv_data_V_keep_V_U_apdone_blk;
wire    regslice_both_recv_data_V_keep_V_U_ack_in_dummy;
wire    regslice_both_recv_data_V_keep_V_U_vld_out;
wire    regslice_both_recv_data_V_strb_V_U_apdone_blk;
wire    regslice_both_recv_data_V_strb_V_U_ack_in_dummy;
wire    regslice_both_recv_data_V_strb_V_U_vld_out;
wire    regslice_both_recv_data_V_last_V_U_apdone_blk;
wire    regslice_both_recv_data_V_last_V_U_ack_in_dummy;
wire    regslice_both_recv_data_V_last_V_U_vld_out;
wire    regslice_both_recv_data_V_dest_V_U_apdone_blk;
wire    regslice_both_recv_data_V_dest_V_U_ack_in_dummy;
wire    regslice_both_recv_data_V_dest_V_U_vld_out;
wire    wr_data_TVALID_int_regslice;
wire    wr_data_TREADY_int_regslice;
wire    regslice_both_wr_data_V_data_V_U_vld_out;
wire    regslice_both_wr_data_V_keep_V_U_apdone_blk;
wire    regslice_both_wr_data_V_keep_V_U_ack_in_dummy;
wire    regslice_both_wr_data_V_keep_V_U_vld_out;
wire    regslice_both_wr_data_V_strb_V_U_apdone_blk;
wire    regslice_both_wr_data_V_strb_V_U_ack_in_dummy;
wire    regslice_both_wr_data_V_strb_V_U_vld_out;
wire    regslice_both_wr_data_V_last_V_U_apdone_blk;
wire    regslice_both_wr_data_V_last_V_U_ack_in_dummy;
wire    regslice_both_wr_data_V_last_V_U_vld_out;
wire    regslice_both_wr_data_V_dest_V_U_apdone_blk;
wire    regslice_both_wr_data_V_dest_V_U_ack_in_dummy;
wire    regslice_both_wr_data_V_dest_V_U_vld_out;
wire   [103:0] wr_cmd_TDATA_int_regslice;
reg    wr_cmd_TVALID_int_regslice;
wire    wr_cmd_TREADY_int_regslice;
wire    regslice_both_wr_cmd_V_data_V_U_vld_out;
wire    regslice_both_wr_cmd_V_keep_V_U_apdone_blk;
wire    regslice_both_wr_cmd_V_keep_V_U_ack_in_dummy;
wire    regslice_both_wr_cmd_V_keep_V_U_vld_out;
wire    regslice_both_wr_cmd_V_strb_V_U_apdone_blk;
wire    regslice_both_wr_cmd_V_strb_V_U_ack_in_dummy;
wire    regslice_both_wr_cmd_V_strb_V_U_vld_out;
wire    regslice_both_wr_cmd_V_last_V_U_apdone_blk;
wire    regslice_both_wr_cmd_V_last_V_U_ack_in_dummy;
wire    regslice_both_wr_cmd_V_last_V_U_vld_out;
wire    regslice_both_wr_cmd_V_dest_V_U_apdone_blk;
wire   [7:0] wr_cmd_TDEST_int_regslice;
wire    regslice_both_wr_cmd_V_dest_V_U_ack_in_dummy;
wire    regslice_both_wr_cmd_V_dest_V_U_vld_out;
wire    regslice_both_rx_V_data_V_U_apdone_blk;
wire   [511:0] rx_TDATA_int_regslice;
wire    rx_TVALID_int_regslice;
reg    rx_TREADY_int_regslice;
wire    regslice_both_rx_V_data_V_U_ack_in;
wire    regslice_both_rx_V_keep_V_U_apdone_blk;
wire   [63:0] rx_TKEEP_int_regslice;
wire    regslice_both_rx_V_keep_V_U_vld_out;
wire    regslice_both_rx_V_keep_V_U_ack_in;
wire    regslice_both_rx_V_strb_V_U_apdone_blk;
wire   [63:0] rx_TSTRB_int_regslice;
wire    regslice_both_rx_V_strb_V_U_vld_out;
wire    regslice_both_rx_V_strb_V_U_ack_in;
wire    regslice_both_rx_V_last_V_U_apdone_blk;
wire   [0:0] rx_TLAST_int_regslice;
wire    regslice_both_rx_V_last_V_U_vld_out;
wire    regslice_both_rx_V_last_V_U_ack_in;
wire    regslice_both_rx_V_dest_V_U_apdone_blk;
wire   [7:0] rx_TDEST_int_regslice;
wire    regslice_both_rx_V_dest_V_U_vld_out;
wire    regslice_both_rx_V_dest_V_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_ap_start_reg = 1'b0;
#0 grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_ap_start_reg = 1'b0;
end

cyt_rdma_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2 grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_ap_start),
    .ap_done(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_ap_done),
    .ap_idle(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_ap_idle),
    .ap_ready(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_ap_ready),
    .rx_TVALID(rx_TVALID_int_regslice),
    .recv_data_TREADY(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TREADY),
    .rx_TDATA(rx_TDATA_int_regslice),
    .rx_TREADY(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_rx_TREADY),
    .rx_TKEEP(rx_TKEEP_int_regslice),
    .rx_TSTRB(rx_TSTRB_int_regslice),
    .rx_TLAST(rx_TLAST_int_regslice),
    .rx_TDEST(rx_TDEST_int_regslice),
    .recv_data_TDATA(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TDATA),
    .recv_data_TVALID(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TVALID),
    .recv_data_TKEEP(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TKEEP),
    .recv_data_TSTRB(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TSTRB),
    .recv_data_TLAST(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TLAST),
    .recv_data_TDEST(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TDEST)
);

cyt_rdma_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1 grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_ap_start),
    .ap_done(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_ap_done),
    .ap_idle(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_ap_idle),
    .ap_ready(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_ap_ready),
    .rx_TVALID(rx_TVALID_int_regslice),
    .wr_data_TREADY(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TREADY),
    .rx_TDATA(rx_TDATA_int_regslice),
    .rx_TREADY(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_rx_TREADY),
    .rx_TKEEP(rx_TKEEP_int_regslice),
    .rx_TSTRB(rx_TSTRB_int_regslice),
    .rx_TLAST(rx_TLAST_int_regslice),
    .rx_TDEST(rx_TDEST_int_regslice),
    .wr_data_TDATA(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TDATA),
    .wr_data_TVALID(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TVALID),
    .wr_data_TKEEP(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TKEEP),
    .wr_data_TSTRB(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TSTRB),
    .wr_data_TLAST(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TLAST),
    .wr_data_TDEST(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TDEST)
);

cyt_rdma_regslice_both #(
    .DataWidth( 64 ))
regslice_both_notif_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(notif_TDATA_int_regslice),
    .vld_in(notif_TVALID_int_regslice),
    .ack_in(notif_TREADY_int_regslice),
    .data_out(notif_TDATA),
    .vld_out(regslice_both_notif_U_vld_out),
    .ack_out(notif_TREADY),
    .apdone_blk(regslice_both_notif_U_apdone_blk)
);

cyt_rdma_regslice_both #(
    .DataWidth( 512 ))
regslice_both_recv_data_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TDATA),
    .vld_in(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TVALID),
    .ack_in(recv_data_TREADY_int_regslice),
    .data_out(recv_data_TDATA),
    .vld_out(regslice_both_recv_data_V_data_V_U_vld_out),
    .ack_out(recv_data_TREADY),
    .apdone_blk(regslice_both_recv_data_V_data_V_U_apdone_blk)
);

cyt_rdma_regslice_both #(
    .DataWidth( 64 ))
regslice_both_recv_data_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TKEEP),
    .vld_in(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TVALID),
    .ack_in(regslice_both_recv_data_V_keep_V_U_ack_in_dummy),
    .data_out(recv_data_TKEEP),
    .vld_out(regslice_both_recv_data_V_keep_V_U_vld_out),
    .ack_out(recv_data_TREADY),
    .apdone_blk(regslice_both_recv_data_V_keep_V_U_apdone_blk)
);

cyt_rdma_regslice_both #(
    .DataWidth( 64 ))
regslice_both_recv_data_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TSTRB),
    .vld_in(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TVALID),
    .ack_in(regslice_both_recv_data_V_strb_V_U_ack_in_dummy),
    .data_out(recv_data_TSTRB),
    .vld_out(regslice_both_recv_data_V_strb_V_U_vld_out),
    .ack_out(recv_data_TREADY),
    .apdone_blk(regslice_both_recv_data_V_strb_V_U_apdone_blk)
);

cyt_rdma_regslice_both #(
    .DataWidth( 1 ))
regslice_both_recv_data_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TLAST),
    .vld_in(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TVALID),
    .ack_in(regslice_both_recv_data_V_last_V_U_ack_in_dummy),
    .data_out(recv_data_TLAST),
    .vld_out(regslice_both_recv_data_V_last_V_U_vld_out),
    .ack_out(recv_data_TREADY),
    .apdone_blk(regslice_both_recv_data_V_last_V_U_apdone_blk)
);

cyt_rdma_regslice_both #(
    .DataWidth( 8 ))
regslice_both_recv_data_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TDEST),
    .vld_in(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TVALID),
    .ack_in(regslice_both_recv_data_V_dest_V_U_ack_in_dummy),
    .data_out(recv_data_TDEST),
    .vld_out(regslice_both_recv_data_V_dest_V_U_vld_out),
    .ack_out(recv_data_TREADY),
    .apdone_blk(regslice_both_recv_data_V_dest_V_U_apdone_blk)
);

cyt_rdma_regslice_both #(
    .DataWidth( 512 ))
regslice_both_wr_data_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TDATA),
    .vld_in(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TVALID),
    .ack_in(wr_data_TREADY_int_regslice),
    .data_out(wr_data_TDATA),
    .vld_out(regslice_both_wr_data_V_data_V_U_vld_out),
    .ack_out(wr_data_TREADY),
    .apdone_blk(regslice_both_wr_data_V_data_V_U_apdone_blk)
);

cyt_rdma_regslice_both #(
    .DataWidth( 64 ))
regslice_both_wr_data_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TKEEP),
    .vld_in(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TVALID),
    .ack_in(regslice_both_wr_data_V_keep_V_U_ack_in_dummy),
    .data_out(wr_data_TKEEP),
    .vld_out(regslice_both_wr_data_V_keep_V_U_vld_out),
    .ack_out(wr_data_TREADY),
    .apdone_blk(regslice_both_wr_data_V_keep_V_U_apdone_blk)
);

cyt_rdma_regslice_both #(
    .DataWidth( 64 ))
regslice_both_wr_data_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TSTRB),
    .vld_in(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TVALID),
    .ack_in(regslice_both_wr_data_V_strb_V_U_ack_in_dummy),
    .data_out(wr_data_TSTRB),
    .vld_out(regslice_both_wr_data_V_strb_V_U_vld_out),
    .ack_out(wr_data_TREADY),
    .apdone_blk(regslice_both_wr_data_V_strb_V_U_apdone_blk)
);

cyt_rdma_regslice_both #(
    .DataWidth( 1 ))
regslice_both_wr_data_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TLAST),
    .vld_in(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TVALID),
    .ack_in(regslice_both_wr_data_V_last_V_U_ack_in_dummy),
    .data_out(wr_data_TLAST),
    .vld_out(regslice_both_wr_data_V_last_V_U_vld_out),
    .ack_out(wr_data_TREADY),
    .apdone_blk(regslice_both_wr_data_V_last_V_U_apdone_blk)
);

cyt_rdma_regslice_both #(
    .DataWidth( 8 ))
regslice_both_wr_data_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TDEST),
    .vld_in(grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TVALID),
    .ack_in(regslice_both_wr_data_V_dest_V_U_ack_in_dummy),
    .data_out(wr_data_TDEST),
    .vld_out(regslice_both_wr_data_V_dest_V_U_vld_out),
    .ack_out(wr_data_TREADY),
    .apdone_blk(regslice_both_wr_data_V_dest_V_U_apdone_blk)
);

cyt_rdma_regslice_both #(
    .DataWidth( 104 ))
regslice_both_wr_cmd_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(wr_cmd_TDATA_int_regslice),
    .vld_in(wr_cmd_TVALID_int_regslice),
    .ack_in(wr_cmd_TREADY_int_regslice),
    .data_out(wr_cmd_TDATA),
    .vld_out(regslice_both_wr_cmd_V_data_V_U_vld_out),
    .ack_out(wr_cmd_TREADY),
    .apdone_blk(regslice_both_wr_cmd_V_data_V_U_apdone_blk)
);

cyt_rdma_regslice_both #(
    .DataWidth( 13 ))
regslice_both_wr_cmd_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(13'd0),
    .vld_in(wr_cmd_TVALID_int_regslice),
    .ack_in(regslice_both_wr_cmd_V_keep_V_U_ack_in_dummy),
    .data_out(wr_cmd_TKEEP),
    .vld_out(regslice_both_wr_cmd_V_keep_V_U_vld_out),
    .ack_out(wr_cmd_TREADY),
    .apdone_blk(regslice_both_wr_cmd_V_keep_V_U_apdone_blk)
);

cyt_rdma_regslice_both #(
    .DataWidth( 13 ))
regslice_both_wr_cmd_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(13'd0),
    .vld_in(wr_cmd_TVALID_int_regslice),
    .ack_in(regslice_both_wr_cmd_V_strb_V_U_ack_in_dummy),
    .data_out(wr_cmd_TSTRB),
    .vld_out(regslice_both_wr_cmd_V_strb_V_U_vld_out),
    .ack_out(wr_cmd_TREADY),
    .apdone_blk(regslice_both_wr_cmd_V_strb_V_U_apdone_blk)
);

cyt_rdma_regslice_both #(
    .DataWidth( 1 ))
regslice_both_wr_cmd_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(1'd1),
    .vld_in(wr_cmd_TVALID_int_regslice),
    .ack_in(regslice_both_wr_cmd_V_last_V_U_ack_in_dummy),
    .data_out(wr_cmd_TLAST),
    .vld_out(regslice_both_wr_cmd_V_last_V_U_vld_out),
    .ack_out(wr_cmd_TREADY),
    .apdone_blk(regslice_both_wr_cmd_V_last_V_U_apdone_blk)
);

cyt_rdma_regslice_both #(
    .DataWidth( 8 ))
regslice_both_wr_cmd_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(wr_cmd_TDEST_int_regslice),
    .vld_in(wr_cmd_TVALID_int_regslice),
    .ack_in(regslice_both_wr_cmd_V_dest_V_U_ack_in_dummy),
    .data_out(wr_cmd_TDEST),
    .vld_out(regslice_both_wr_cmd_V_dest_V_U_vld_out),
    .ack_out(wr_cmd_TREADY),
    .apdone_blk(regslice_both_wr_cmd_V_dest_V_U_apdone_blk)
);

cyt_rdma_regslice_both #(
    .DataWidth( 512 ))
regslice_both_rx_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(rx_TDATA),
    .vld_in(rx_TVALID),
    .ack_in(regslice_both_rx_V_data_V_U_ack_in),
    .data_out(rx_TDATA_int_regslice),
    .vld_out(rx_TVALID_int_regslice),
    .ack_out(rx_TREADY_int_regslice),
    .apdone_blk(regslice_both_rx_V_data_V_U_apdone_blk)
);

cyt_rdma_regslice_both #(
    .DataWidth( 64 ))
regslice_both_rx_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(rx_TKEEP),
    .vld_in(rx_TVALID),
    .ack_in(regslice_both_rx_V_keep_V_U_ack_in),
    .data_out(rx_TKEEP_int_regslice),
    .vld_out(regslice_both_rx_V_keep_V_U_vld_out),
    .ack_out(rx_TREADY_int_regslice),
    .apdone_blk(regslice_both_rx_V_keep_V_U_apdone_blk)
);

cyt_rdma_regslice_both #(
    .DataWidth( 64 ))
regslice_both_rx_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(rx_TSTRB),
    .vld_in(rx_TVALID),
    .ack_in(regslice_both_rx_V_strb_V_U_ack_in),
    .data_out(rx_TSTRB_int_regslice),
    .vld_out(regslice_both_rx_V_strb_V_U_vld_out),
    .ack_out(rx_TREADY_int_regslice),
    .apdone_blk(regslice_both_rx_V_strb_V_U_apdone_blk)
);

cyt_rdma_regslice_both #(
    .DataWidth( 1 ))
regslice_both_rx_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(rx_TLAST),
    .vld_in(rx_TVALID),
    .ack_in(regslice_both_rx_V_last_V_U_ack_in),
    .data_out(rx_TLAST_int_regslice),
    .vld_out(regslice_both_rx_V_last_V_U_vld_out),
    .ack_out(rx_TREADY_int_regslice),
    .apdone_blk(regslice_both_rx_V_last_V_U_apdone_blk)
);

cyt_rdma_regslice_both #(
    .DataWidth( 8 ))
regslice_both_rx_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(rx_TDEST),
    .vld_in(rx_TVALID),
    .ack_in(regslice_both_rx_V_dest_V_U_ack_in),
    .data_out(rx_TDEST_int_regslice),
    .vld_out(regslice_both_rx_V_dest_V_U_vld_out),
    .ack_out(rx_TREADY_int_regslice),
    .apdone_blk(regslice_both_rx_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((regslice_both_wr_cmd_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_wr_data_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_recv_data_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_notif_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state5))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_ap_start_reg <= 1'b0;
    end else begin
        if (((wr_cmd_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
            grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_ap_start_reg <= 1'b1;
        end else if ((grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_ap_ready == 1'b1)) begin
            grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_ap_start_reg <= 1'b0;
    end else begin
        if (((notif_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_ap_start_reg <= 1'b1;
        end else if ((grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_ap_ready == 1'b1)) begin
            grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_nbreadreq_fu_128_p7 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp_ln1019_reg_350 <= icmp_ln1019_fu_302_p2;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state1_io) | (ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((tmp_nbreadreq_fu_128_p7 == 1'd1) & (rx_TVALID_int_regslice == 1'b0)) | ((wr_cmd_TREADY_int_regslice == 1'b0) & (ap_predicate_op35_write_state1 == 1'b1)) | ((notif_TREADY_int_regslice == 1'b0) & (ap_predicate_op32_write_state1 == 1'b1)))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((notif_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state3_on_subcall_done)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((wr_cmd_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_wr_cmd_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_wr_data_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_recv_data_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_notif_U_apdone_blk == 1'b1))) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((regslice_both_wr_cmd_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_wr_data_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_recv_data_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_notif_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((regslice_both_wr_cmd_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_wr_data_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_recv_data_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_notif_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (icmp_ln1019_fu_302_p2 == 1'd0) & (tmp_nbreadreq_fu_128_p7 == 1'd1) & (1'b1 == ap_CS_fsm_state1)))) begin
        notif_TDATA_blk_n = notif_TREADY_int_regslice;
    end else begin
        notif_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_io) | (ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((tmp_nbreadreq_fu_128_p7 == 1'd1) & (rx_TVALID_int_regslice == 1'b0)) | ((wr_cmd_TREADY_int_regslice == 1'b0) & (ap_predicate_op35_write_state1 == 1'b1)) | ((notif_TREADY_int_regslice == 1'b0) & (ap_predicate_op32_write_state1 == 1'b1))) & (1'b1 == ap_CS_fsm_state1) & (ap_predicate_op32_write_state1 == 1'b1))) begin
        notif_TVALID_int_regslice = 1'b1;
    end else begin
        notif_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (tmp_nbreadreq_fu_128_p7 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        rx_TDATA_blk_n = rx_TVALID_int_regslice;
    end else begin
        rx_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_io) | (ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((tmp_nbreadreq_fu_128_p7 == 1'd1) & (rx_TVALID_int_regslice == 1'b0)) | ((wr_cmd_TREADY_int_regslice == 1'b0) & (ap_predicate_op35_write_state1 == 1'b1)) | ((notif_TREADY_int_regslice == 1'b0) & (ap_predicate_op32_write_state1 == 1'b1))) & (tmp_nbreadreq_fu_128_p7 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        rx_TREADY_int_regslice = 1'b1;
    end else if (((icmp_ln1019_reg_350 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        rx_TREADY_int_regslice = grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_rx_TREADY;
    end else if (((icmp_ln1019_reg_350 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        rx_TREADY_int_regslice = grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_rx_TREADY;
    end else begin
        rx_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (icmp_ln1019_fu_302_p2 == 1'd1) & (tmp_nbreadreq_fu_128_p7 == 1'd1) & (1'b1 == ap_CS_fsm_state1)))) begin
        wr_cmd_TDATA_blk_n = wr_cmd_TREADY_int_regslice;
    end else begin
        wr_cmd_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_io) | (ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((tmp_nbreadreq_fu_128_p7 == 1'd1) & (rx_TVALID_int_regslice == 1'b0)) | ((wr_cmd_TREADY_int_regslice == 1'b0) & (ap_predicate_op35_write_state1 == 1'b1)) | ((notif_TREADY_int_regslice == 1'b0) & (ap_predicate_op32_write_state1 == 1'b1))) & (1'b1 == ap_CS_fsm_state1) & (ap_predicate_op35_write_state1 == 1'b1))) begin
        wr_cmd_TVALID_int_regslice = 1'b1;
    end else begin
        wr_cmd_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((1'b1 == ap_block_state1_io) | (ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((tmp_nbreadreq_fu_128_p7 == 1'd1) & (rx_TVALID_int_regslice == 1'b0)) | ((wr_cmd_TREADY_int_regslice == 1'b0) & (ap_predicate_op35_write_state1 == 1'b1)) | ((notif_TREADY_int_regslice == 1'b0) & (ap_predicate_op32_write_state1 == 1'b1))) & (icmp_ln1019_fu_302_p2 == 1'd1) & (tmp_nbreadreq_fu_128_p7 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if ((~((1'b1 == ap_block_state1_io) | (ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((tmp_nbreadreq_fu_128_p7 == 1'd1) & (rx_TVALID_int_regslice == 1'b0)) | ((wr_cmd_TREADY_int_regslice == 1'b0) & (ap_predicate_op35_write_state1 == 1'b1)) | ((notif_TREADY_int_regslice == 1'b0) & (ap_predicate_op32_write_state1 == 1'b1))) & (icmp_ln1019_fu_302_p2 == 1'd0) & (tmp_nbreadreq_fu_128_p7 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if ((~((1'b1 == ap_block_state1_io) | (ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((tmp_nbreadreq_fu_128_p7 == 1'd1) & (rx_TVALID_int_regslice == 1'b0)) | ((wr_cmd_TREADY_int_regslice == 1'b0) & (ap_predicate_op35_write_state1 == 1'b1)) | ((notif_TREADY_int_regslice == 1'b0) & (ap_predicate_op32_write_state1 == 1'b1))) & (tmp_nbreadreq_fu_128_p7 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((notif_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((wr_cmd_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if ((~((regslice_both_wr_cmd_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_wr_data_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_recv_data_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_notif_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((tmp_nbreadreq_fu_128_p7 == 1'd1) & (rx_TVALID_int_regslice == 1'b0)) | ((wr_cmd_TREADY_int_regslice == 1'b0) & (ap_predicate_op35_write_state1 == 1'b1)) | ((notif_TREADY_int_regslice == 1'b0) & (ap_predicate_op32_write_state1 == 1'b1)));
end

always @ (*) begin
    ap_block_state1_io = (((wr_cmd_TREADY_int_regslice == 1'b0) & (ap_predicate_op35_write_state1 == 1'b1)) | ((notif_TREADY_int_regslice == 1'b0) & (ap_predicate_op32_write_state1 == 1'b1)));
end

always @ (*) begin
    ap_block_state3_on_subcall_done = (((icmp_ln1019_reg_350 == 1'd1) & (grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_ap_done == 1'b0)) | ((icmp_ln1019_reg_350 == 1'd0) & (grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_ap_done == 1'b0)));
end

always @ (*) begin
    ap_block_state5 = ((regslice_both_wr_cmd_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_wr_data_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_recv_data_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_notif_U_apdone_blk == 1'b1));
end

always @ (*) begin
    ap_predicate_op32_write_state1 = ((icmp_ln1019_fu_302_p2 == 1'd0) & (tmp_nbreadreq_fu_128_p7 == 1'd1));
end

always @ (*) begin
    ap_predicate_op35_write_state1 = ((icmp_ln1019_fu_302_p2 == 1'd1) & (tmp_nbreadreq_fu_128_p7 == 1'd1));
end

assign command_len_V_1_fu_247_p4 = {{rx_TDATA_int_regslice[95:64]}};

assign command_opcode_V_1_fu_268_p4 = {{rx_TDATA_int_regslice[127:120]}};

assign command_vaddr_V_1_fu_243_p1 = rx_TDATA_int_regslice[63:0];

assign current_notif_length_V_fu_294_p3 = ((icmp_ln200_fu_278_p2[0:0] == 1'b1) ? 23'd4096 : trunc_ln_fu_284_p4);

assign grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_ap_start = grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_ap_start_reg;

assign grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TREADY = (wr_data_TREADY_int_regslice & ap_CS_fsm_state3);

assign grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_ap_start = grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_ap_start_reg;

assign grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TREADY = (recv_data_TREADY_int_regslice & ap_CS_fsm_state3);

assign icmp_ln1019_fu_302_p2 = ((command_opcode_V_1_fu_268_p4 == 8'd1) ? 1'b1 : 1'b0);

assign icmp_ln200_fu_278_p2 = ((command_len_V_1_fu_247_p4 > 32'd4096) ? 1'b1 : 1'b0);

assign notif_TDATA_int_regslice = or_ln_fu_308_p5;

assign notif_TVALID = regslice_both_notif_U_vld_out;

assign or_ln_fu_308_p5 = {{{{current_notif_length_V_fu_294_p3}, {8'd0}}, {rx_TDEST_int_regslice}}, {16'd0}};

assign p_Result_s_fu_325_p5 = {{{{{{1'd0}, {command_vaddr_V_1_fu_243_p1}}}, {9'd385}}}, {current_notif_length_V_fu_294_p3}};

assign recv_data_TVALID = regslice_both_recv_data_V_data_V_U_vld_out;

assign recv_data_TVALID_int_regslice = grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_128_2_fu_187_recv_data_TVALID;

assign rx_TREADY = regslice_both_rx_V_data_V_U_ack_in;

assign tmp_nbreadreq_fu_128_p7 = rx_TVALID_int_regslice;

assign trunc_ln_fu_284_p4 = {{rx_TDATA_int_regslice[86:64]}};

assign wr_cmd_TDATA_int_regslice = p_Result_s_fu_325_p5;

assign wr_cmd_TDEST_int_regslice = {{rx_TDATA_int_regslice[103:96]}};

assign wr_cmd_TVALID = regslice_both_wr_cmd_V_data_V_U_vld_out;

assign wr_data_TVALID = regslice_both_wr_data_V_data_V_U_vld_out;

assign wr_data_TVALID_int_regslice = grp_cyt_rdma_rx_Pipeline_VITIS_LOOP_119_1_fu_211_wr_data_TVALID;

endmodule //cyt_rdma_cyt_rdma_rx
