// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module cyt_rdma_cyt_rdma_tx (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        rdma_sq_TDATA,
        rdma_sq_TVALID,
        rdma_sq_TREADY,
        send_data_TDATA,
        send_data_TVALID,
        send_data_TREADY,
        send_data_TKEEP,
        send_data_TSTRB,
        send_data_TLAST,
        send_data_TDEST,
        tx_TDATA,
        tx_TVALID,
        tx_TREADY,
        tx_TKEEP,
        tx_TSTRB,
        tx_TLAST,
        tx_TDEST
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [127:0] rdma_sq_TDATA;
input   rdma_sq_TVALID;
output   rdma_sq_TREADY;
input  [511:0] send_data_TDATA;
input   send_data_TVALID;
output   send_data_TREADY;
input  [63:0] send_data_TKEEP;
input  [63:0] send_data_TSTRB;
input  [0:0] send_data_TLAST;
input  [7:0] send_data_TDEST;
output  [511:0] tx_TDATA;
output   tx_TVALID;
input   tx_TREADY;
output  [63:0] tx_TKEEP;
output  [63:0] tx_TSTRB;
output  [0:0] tx_TLAST;
output  [7:0] tx_TDEST;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [0:0] txFsmState;
reg   [31:0] command_len_V;
reg   [63:0] command_vaddr_V;
reg   [7:0] command_host_V;
reg   [15:0] command_qpn_V;
reg   [7:0] command_opcode_V;
reg    rdma_sq_TDATA_blk_n;
wire   [0:0] txFsmState_load_load_fu_224_p1;
wire   [0:0] tmp_1_nbreadreq_fu_130_p3;
reg    tx_TDATA_blk_n;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [0:0] txFsmState_load_reg_451;
reg   [31:0] command_len_V_load_reg_455;
wire   [0:0] tmp_nbreadreq_fu_144_p7;
reg   [0:0] tmp_reg_463;
wire   [0:0] grp_nbwritereq_fu_160_p7;
reg   [0:0] tmp_2_reg_467;
wire    ap_CS_fsm_state2;
wire   [7:0] tx_word_dest_V_fu_316_p1;
reg   [7:0] tx_word_dest_V_reg_494;
wire   [511:0] zext_ln186_fu_362_p1;
wire    grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_start;
wire    grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_done;
wire    grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_idle;
wire    grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_ready;
wire    grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TREADY;
wire    grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_send_data_TREADY;
wire   [511:0] grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TDATA;
wire    grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TVALID;
wire   [63:0] grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TKEEP;
wire   [63:0] grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TSTRB;
wire   [0:0] grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TLAST;
wire   [7:0] grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TDEST;
wire   [63:0] grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tmp_strb_V_out;
wire    grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tmp_strb_V_out_ap_vld;
wire   [31:0] grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_i_1_out;
wire    grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_i_1_out_ap_vld;
reg    grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg   [63:0] tmp_strb_V_loc_fu_114;
reg   [31:0] i_1_loc_fu_110;
wire    ap_CS_fsm_state7;
wire    regslice_both_tx_V_data_V_U_apdone_blk;
wire   [0:0] icmp_ln1035_fu_400_p2;
reg    ap_predicate_op21_read_state1;
reg    ap_block_state1;
wire   [63:0] add_ln840_fu_395_p2;
wire   [63:0] trunc_ln47_fu_232_p1;
reg   [63:0] tmp_strb_V_fu_118;
reg   [63:0] empty_fu_122;
reg   [31:0] empty_23_fu_126;
wire   [31:0] select_ln73_fu_383_p3;
wire   [127:0] p_Result_s_fu_351_p6;
wire   [0:0] icmp_ln1027_fu_373_p2;
wire   [31:0] sub_ln73_fu_378_p2;
wire   [63:0] zext_ln840_fu_391_p1;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    regslice_both_rdma_sq_U_apdone_blk;
wire   [127:0] rdma_sq_TDATA_int_regslice;
wire    rdma_sq_TVALID_int_regslice;
reg    rdma_sq_TREADY_int_regslice;
wire    regslice_both_rdma_sq_U_ack_in;
wire    regslice_both_send_data_V_data_V_U_apdone_blk;
wire   [511:0] send_data_TDATA_int_regslice;
wire    send_data_TVALID_int_regslice;
reg    send_data_TREADY_int_regslice;
wire    regslice_both_send_data_V_data_V_U_ack_in;
wire    regslice_both_send_data_V_keep_V_U_apdone_blk;
wire   [63:0] send_data_TKEEP_int_regslice;
wire    regslice_both_send_data_V_keep_V_U_vld_out;
wire    regslice_both_send_data_V_keep_V_U_ack_in;
wire    regslice_both_send_data_V_strb_V_U_apdone_blk;
wire   [63:0] send_data_TSTRB_int_regslice;
wire    regslice_both_send_data_V_strb_V_U_vld_out;
wire    regslice_both_send_data_V_strb_V_U_ack_in;
wire    regslice_both_send_data_V_last_V_U_apdone_blk;
wire   [0:0] send_data_TLAST_int_regslice;
wire    regslice_both_send_data_V_last_V_U_vld_out;
wire    regslice_both_send_data_V_last_V_U_ack_in;
wire    regslice_both_send_data_V_dest_V_U_apdone_blk;
wire   [7:0] send_data_TDEST_int_regslice;
wire    regslice_both_send_data_V_dest_V_U_vld_out;
wire    regslice_both_send_data_V_dest_V_U_ack_in;
reg   [511:0] tx_TDATA_int_regslice;
reg    tx_TVALID_int_regslice;
wire    tx_TREADY_int_regslice;
wire    regslice_both_tx_V_data_V_U_vld_out;
wire    regslice_both_tx_V_keep_V_U_apdone_blk;
reg   [63:0] tx_TKEEP_int_regslice;
wire    regslice_both_tx_V_keep_V_U_ack_in_dummy;
wire    regslice_both_tx_V_keep_V_U_vld_out;
wire    regslice_both_tx_V_strb_V_U_apdone_blk;
reg   [63:0] tx_TSTRB_int_regslice;
wire    regslice_both_tx_V_strb_V_U_ack_in_dummy;
wire    regslice_both_tx_V_strb_V_U_vld_out;
wire    regslice_both_tx_V_last_V_U_apdone_blk;
reg   [0:0] tx_TLAST_int_regslice;
wire    regslice_both_tx_V_last_V_U_ack_in_dummy;
wire    regslice_both_tx_V_last_V_U_vld_out;
wire    regslice_both_tx_V_dest_V_U_apdone_blk;
reg   [7:0] tx_TDEST_int_regslice;
wire    regslice_both_tx_V_dest_V_U_ack_in_dummy;
wire    regslice_both_tx_V_dest_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 7'd1;
#0 txFsmState = 1'd0;
#0 command_len_V = 32'd0;
#0 command_vaddr_V = 64'd0;
#0 command_host_V = 8'd0;
#0 command_qpn_V = 16'd0;
#0 command_opcode_V = 8'd0;
#0 grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_start_reg = 1'b0;
end

cyt_rdma_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2 grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_start),
    .ap_done(grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_done),
    .ap_idle(grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_idle),
    .ap_ready(grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_ready),
    .send_data_TVALID(send_data_TVALID_int_regslice),
    .tx_TREADY(grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TREADY),
    .send_data_TDATA(send_data_TDATA_int_regslice),
    .send_data_TREADY(grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_send_data_TREADY),
    .send_data_TKEEP(send_data_TKEEP_int_regslice),
    .send_data_TSTRB(send_data_TSTRB_int_regslice),
    .send_data_TLAST(send_data_TLAST_int_regslice),
    .send_data_TDEST(send_data_TDEST_int_regslice),
    .tx_word_dest_V(tx_word_dest_V_reg_494),
    .tx_TDATA(grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TDATA),
    .tx_TVALID(grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TVALID),
    .tx_TKEEP(grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TKEEP),
    .tx_TSTRB(grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TSTRB),
    .tx_TLAST(grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TLAST),
    .tx_TDEST(grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TDEST),
    .tmp_strb_V_out(grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tmp_strb_V_out),
    .tmp_strb_V_out_ap_vld(grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tmp_strb_V_out_ap_vld),
    .i_1_out(grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_i_1_out),
    .i_1_out_ap_vld(grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_i_1_out_ap_vld)
);

cyt_rdma_regslice_both #(
    .DataWidth( 128 ))
regslice_both_rdma_sq_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(rdma_sq_TDATA),
    .vld_in(rdma_sq_TVALID),
    .ack_in(regslice_both_rdma_sq_U_ack_in),
    .data_out(rdma_sq_TDATA_int_regslice),
    .vld_out(rdma_sq_TVALID_int_regslice),
    .ack_out(rdma_sq_TREADY_int_regslice),
    .apdone_blk(regslice_both_rdma_sq_U_apdone_blk)
);

cyt_rdma_regslice_both #(
    .DataWidth( 512 ))
regslice_both_send_data_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(send_data_TDATA),
    .vld_in(send_data_TVALID),
    .ack_in(regslice_both_send_data_V_data_V_U_ack_in),
    .data_out(send_data_TDATA_int_regslice),
    .vld_out(send_data_TVALID_int_regslice),
    .ack_out(send_data_TREADY_int_regslice),
    .apdone_blk(regslice_both_send_data_V_data_V_U_apdone_blk)
);

cyt_rdma_regslice_both #(
    .DataWidth( 64 ))
regslice_both_send_data_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(send_data_TKEEP),
    .vld_in(send_data_TVALID),
    .ack_in(regslice_both_send_data_V_keep_V_U_ack_in),
    .data_out(send_data_TKEEP_int_regslice),
    .vld_out(regslice_both_send_data_V_keep_V_U_vld_out),
    .ack_out(send_data_TREADY_int_regslice),
    .apdone_blk(regslice_both_send_data_V_keep_V_U_apdone_blk)
);

cyt_rdma_regslice_both #(
    .DataWidth( 64 ))
regslice_both_send_data_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(send_data_TSTRB),
    .vld_in(send_data_TVALID),
    .ack_in(regslice_both_send_data_V_strb_V_U_ack_in),
    .data_out(send_data_TSTRB_int_regslice),
    .vld_out(regslice_both_send_data_V_strb_V_U_vld_out),
    .ack_out(send_data_TREADY_int_regslice),
    .apdone_blk(regslice_both_send_data_V_strb_V_U_apdone_blk)
);

cyt_rdma_regslice_both #(
    .DataWidth( 1 ))
regslice_both_send_data_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(send_data_TLAST),
    .vld_in(send_data_TVALID),
    .ack_in(regslice_both_send_data_V_last_V_U_ack_in),
    .data_out(send_data_TLAST_int_regslice),
    .vld_out(regslice_both_send_data_V_last_V_U_vld_out),
    .ack_out(send_data_TREADY_int_regslice),
    .apdone_blk(regslice_both_send_data_V_last_V_U_apdone_blk)
);

cyt_rdma_regslice_both #(
    .DataWidth( 8 ))
regslice_both_send_data_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(send_data_TDEST),
    .vld_in(send_data_TVALID),
    .ack_in(regslice_both_send_data_V_dest_V_U_ack_in),
    .data_out(send_data_TDEST_int_regslice),
    .vld_out(regslice_both_send_data_V_dest_V_U_vld_out),
    .ack_out(send_data_TREADY_int_regslice),
    .apdone_blk(regslice_both_send_data_V_dest_V_U_apdone_blk)
);

cyt_rdma_regslice_both #(
    .DataWidth( 512 ))
regslice_both_tx_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(tx_TDATA_int_regslice),
    .vld_in(tx_TVALID_int_regslice),
    .ack_in(tx_TREADY_int_regslice),
    .data_out(tx_TDATA),
    .vld_out(regslice_both_tx_V_data_V_U_vld_out),
    .ack_out(tx_TREADY),
    .apdone_blk(regslice_both_tx_V_data_V_U_apdone_blk)
);

cyt_rdma_regslice_both #(
    .DataWidth( 64 ))
regslice_both_tx_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(tx_TKEEP_int_regslice),
    .vld_in(tx_TVALID_int_regslice),
    .ack_in(regslice_both_tx_V_keep_V_U_ack_in_dummy),
    .data_out(tx_TKEEP),
    .vld_out(regslice_both_tx_V_keep_V_U_vld_out),
    .ack_out(tx_TREADY),
    .apdone_blk(regslice_both_tx_V_keep_V_U_apdone_blk)
);

cyt_rdma_regslice_both #(
    .DataWidth( 64 ))
regslice_both_tx_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(tx_TSTRB_int_regslice),
    .vld_in(tx_TVALID_int_regslice),
    .ack_in(regslice_both_tx_V_strb_V_U_ack_in_dummy),
    .data_out(tx_TSTRB),
    .vld_out(regslice_both_tx_V_strb_V_U_vld_out),
    .ack_out(tx_TREADY),
    .apdone_blk(regslice_both_tx_V_strb_V_U_apdone_blk)
);

cyt_rdma_regslice_both #(
    .DataWidth( 1 ))
regslice_both_tx_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(tx_TLAST_int_regslice),
    .vld_in(tx_TVALID_int_regslice),
    .ack_in(regslice_both_tx_V_last_V_U_ack_in_dummy),
    .data_out(tx_TLAST),
    .vld_out(regslice_both_tx_V_last_V_U_vld_out),
    .ack_out(tx_TREADY),
    .apdone_blk(regslice_both_tx_V_last_V_U_apdone_blk)
);

cyt_rdma_regslice_both #(
    .DataWidth( 8 ))
regslice_both_tx_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(tx_TDEST_int_regslice),
    .vld_in(tx_TVALID_int_regslice),
    .ack_in(regslice_both_tx_V_dest_V_U_ack_in_dummy),
    .data_out(tx_TDEST),
    .vld_out(regslice_both_tx_V_dest_V_U_vld_out),
    .ack_out(tx_TREADY),
    .apdone_blk(regslice_both_tx_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state7) & (regslice_both_tx_V_data_V_U_apdone_blk == 1'b0) & ((txFsmState_load_reg_451 == 1'd0) | ((tmp_reg_463 == 1'd0) | ((tmp_2_reg_467 == 1'd0) | (icmp_ln1035_fu_400_p2 == 1'd1)))))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_start_reg <= 1'b1;
        end else if ((grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_ready == 1'b1)) begin
            grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((rdma_sq_TVALID_int_regslice == 1'b0) & (ap_predicate_op21_read_state1 == 1'b1))) & (tmp_1_nbreadreq_fu_130_p3 == 1'd1) & (txFsmState == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        command_len_V <= {{rdma_sq_TDATA_int_regslice[95:64]}};
    end else if (((tmp_2_reg_467 == 1'd1) & (tmp_reg_463 == 1'd1) & (txFsmState_load_reg_451 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (icmp_ln1035_fu_400_p2 == 1'd1) & (regslice_both_tx_V_data_V_U_apdone_blk == 1'b0))) begin
        command_len_V <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((rdma_sq_TVALID_int_regslice == 1'b0) & (ap_predicate_op21_read_state1 == 1'b1))) & (tmp_1_nbreadreq_fu_130_p3 == 1'd1) & (txFsmState == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        command_vaddr_V <= trunc_ln47_fu_232_p1;
    end else if (((tmp_2_reg_467 == 1'd1) & (tmp_reg_463 == 1'd1) & (txFsmState_load_reg_451 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (icmp_ln1035_fu_400_p2 == 1'd1) & (regslice_both_tx_V_data_V_U_apdone_blk == 1'b0))) begin
        command_vaddr_V <= add_ln840_fu_395_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_nbwritereq_fu_160_p7 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        empty_23_fu_126 <= command_len_V_load_reg_455;
    end else if (((tmp_2_reg_467 == 1'd1) & (tmp_reg_463 == 1'd1) & (txFsmState_load_reg_451 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (icmp_ln1035_fu_400_p2 == 1'd0) & (regslice_both_tx_V_data_V_U_apdone_blk == 1'b0))) begin
        empty_23_fu_126 <= select_ln73_fu_383_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_nbwritereq_fu_160_p7 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        empty_fu_122 <= command_vaddr_V;
    end else if (((tmp_2_reg_467 == 1'd1) & (tmp_reg_463 == 1'd1) & (txFsmState_load_reg_451 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (icmp_ln1035_fu_400_p2 == 1'd0) & (regslice_both_tx_V_data_V_U_apdone_blk == 1'b0))) begin
        empty_fu_122 <= add_ln840_fu_395_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((rdma_sq_TVALID_int_regslice == 1'b0) & (ap_predicate_op21_read_state1 == 1'b1))) & (tmp_1_nbreadreq_fu_130_p3 == 1'd1) & (txFsmState == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        txFsmState <= 1'd1;
    end else if (((tmp_2_reg_467 == 1'd1) & (tmp_reg_463 == 1'd1) & (txFsmState_load_reg_451 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (icmp_ln1035_fu_400_p2 == 1'd1) & (regslice_both_tx_V_data_V_U_apdone_blk == 1'b0))) begin
        txFsmState <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((rdma_sq_TVALID_int_regslice == 1'b0) & (ap_predicate_op21_read_state1 == 1'b1))) & (tmp_1_nbreadreq_fu_130_p3 == 1'd1) & (txFsmState == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        command_host_V <= {{rdma_sq_TDATA_int_regslice[103:96]}};
        command_opcode_V <= {{rdma_sq_TDATA_int_regslice[127:120]}};
        command_qpn_V <= {{rdma_sq_TDATA_int_regslice[119:104]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        command_len_V_load_reg_455 <= command_len_V;
        txFsmState_load_reg_451 <= txFsmState;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_i_1_out_ap_vld == 1'b1))) begin
        i_1_loc_fu_110 <= grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_i_1_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_2_reg_467 <= tx_TREADY_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if (((txFsmState_load_load_fu_224_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_reg_463 <= tmp_nbreadreq_fu_144_p7;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_467 == 1'd1) & (tmp_reg_463 == 1'd1) & (txFsmState_load_reg_451 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (icmp_ln1035_fu_400_p2 == 1'd0) & (regslice_both_tx_V_data_V_U_apdone_blk == 1'b0))) begin
        tmp_strb_V_fu_118 <= tmp_strb_V_loc_fu_114;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tmp_strb_V_out_ap_vld == 1'b1))) begin
        tmp_strb_V_loc_fu_114 <= grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tmp_strb_V_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_nbwritereq_fu_160_p7 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        tx_word_dest_V_reg_494 <= tx_word_dest_V_fu_316_p1;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((rdma_sq_TVALID_int_regslice == 1'b0) & (ap_predicate_op21_read_state1 == 1'b1)))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((tx_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((tx_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_tx_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (regslice_both_tx_V_data_V_U_apdone_blk == 1'b0) & ((txFsmState_load_reg_451 == 1'd0) | ((tmp_reg_463 == 1'd0) | ((tmp_2_reg_467 == 1'd0) | (icmp_ln1035_fu_400_p2 == 1'd1)))))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (regslice_both_tx_V_data_V_U_apdone_blk == 1'b0) & ((txFsmState_load_reg_451 == 1'd0) | ((tmp_reg_463 == 1'd0) | ((tmp_2_reg_467 == 1'd0) | (icmp_ln1035_fu_400_p2 == 1'd1)))))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (tmp_1_nbreadreq_fu_130_p3 == 1'd1) & (txFsmState == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        rdma_sq_TDATA_blk_n = rdma_sq_TVALID_int_regslice;
    end else begin
        rdma_sq_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((rdma_sq_TVALID_int_regslice == 1'b0) & (ap_predicate_op21_read_state1 == 1'b1))) & (1'b1 == ap_CS_fsm_state1) & (ap_predicate_op21_read_state1 == 1'b1))) begin
        rdma_sq_TREADY_int_regslice = 1'b1;
    end else begin
        rdma_sq_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        send_data_TREADY_int_regslice = grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_send_data_TREADY;
    end else begin
        send_data_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        tx_TDATA_blk_n = tx_TREADY_int_regslice;
    end else begin
        tx_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tx_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        tx_TDATA_int_regslice = zext_ln186_fu_362_p1;
    end else if (((1'b1 == ap_CS_fsm_state6) & (grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TVALID == 1'b1))) begin
        tx_TDATA_int_regslice = grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TDATA;
    end else begin
        tx_TDATA_int_regslice = 'bx;
    end
end

always @ (*) begin
    if (((tx_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        tx_TDEST_int_regslice = tx_word_dest_V_reg_494;
    end else if (((1'b1 == ap_CS_fsm_state6) & (grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TVALID == 1'b1))) begin
        tx_TDEST_int_regslice = grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TDEST;
    end else begin
        tx_TDEST_int_regslice = 'bx;
    end
end

always @ (*) begin
    if (((tx_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        tx_TKEEP_int_regslice = 64'd18446744073709551615;
    end else if (((1'b1 == ap_CS_fsm_state6) & (grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TVALID == 1'b1))) begin
        tx_TKEEP_int_regslice = grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TKEEP;
    end else begin
        tx_TKEEP_int_regslice = 'bx;
    end
end

always @ (*) begin
    if (((tx_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        tx_TLAST_int_regslice = 1'd0;
    end else if (((1'b1 == ap_CS_fsm_state6) & (grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TVALID == 1'b1))) begin
        tx_TLAST_int_regslice = grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TLAST;
    end else begin
        tx_TLAST_int_regslice = 'bx;
    end
end

always @ (*) begin
    if (((tx_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        tx_TSTRB_int_regslice = tmp_strb_V_fu_118;
    end else if (((1'b1 == ap_CS_fsm_state6) & (grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TVALID == 1'b1))) begin
        tx_TSTRB_int_regslice = grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TSTRB;
    end else begin
        tx_TSTRB_int_regslice = 'bx;
    end
end

always @ (*) begin
    if (((tx_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        tx_TVALID_int_regslice = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        tx_TVALID_int_regslice = grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TVALID;
    end else begin
        tx_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((rdma_sq_TVALID_int_regslice == 1'b0) & (ap_predicate_op21_read_state1 == 1'b1))) & (tmp_nbreadreq_fu_144_p7 == 1'd1) & (txFsmState_load_load_fu_224_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((rdma_sq_TVALID_int_regslice == 1'b0) & (ap_predicate_op21_read_state1 == 1'b1))) & (1'b1 == ap_CS_fsm_state1) & ((tmp_nbreadreq_fu_144_p7 == 1'd0) | (txFsmState == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_nbwritereq_fu_160_p7 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((tx_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((tx_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (regslice_both_tx_V_data_V_U_apdone_blk == 1'b0) & ((txFsmState_load_reg_451 == 1'd0) | ((tmp_reg_463 == 1'd0) | ((tmp_2_reg_467 == 1'd0) | (icmp_ln1035_fu_400_p2 == 1'd1)))))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((tmp_2_reg_467 == 1'd1) & (tmp_reg_463 == 1'd1) & (txFsmState_load_reg_451 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (icmp_ln1035_fu_400_p2 == 1'd0) & (regslice_both_tx_V_data_V_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln840_fu_395_p2 = (zext_ln840_fu_391_p1 + empty_fu_122);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((rdma_sq_TVALID_int_regslice == 1'b0) & (ap_predicate_op21_read_state1 == 1'b1)));
end

always @ (*) begin
    ap_predicate_op21_read_state1 = ((tmp_1_nbreadreq_fu_130_p3 == 1'd1) & (txFsmState == 1'd0));
end

assign grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_start = grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_ap_start_reg;

assign grp_cyt_rdma_tx_Pipeline_VITIS_LOOP_65_2_fu_197_tx_TREADY = (tx_TREADY_int_regslice & ap_CS_fsm_state6);

assign grp_nbwritereq_fu_160_p7 = tx_TREADY_int_regslice;

assign icmp_ln1027_fu_373_p2 = ((empty_23_fu_126 < i_1_loc_fu_110) ? 1'b1 : 1'b0);

assign icmp_ln1035_fu_400_p2 = ((select_ln73_fu_383_p3 == 32'd0) ? 1'b1 : 1'b0);

assign p_Result_s_fu_351_p6 = {{{{{command_opcode_V}, {command_qpn_V}}, {command_host_V}}, {empty_23_fu_126}}, {empty_fu_122}};

assign rdma_sq_TREADY = regslice_both_rdma_sq_U_ack_in;

assign select_ln73_fu_383_p3 = ((icmp_ln1027_fu_373_p2[0:0] == 1'b1) ? 32'd0 : sub_ln73_fu_378_p2);

assign send_data_TREADY = regslice_both_send_data_V_data_V_U_ack_in;

assign sub_ln73_fu_378_p2 = (empty_23_fu_126 - i_1_loc_fu_110);

assign tmp_1_nbreadreq_fu_130_p3 = rdma_sq_TVALID_int_regslice;

assign tmp_nbreadreq_fu_144_p7 = send_data_TVALID_int_regslice;

assign trunc_ln47_fu_232_p1 = rdma_sq_TDATA_int_regslice[63:0];

assign txFsmState_load_load_fu_224_p1 = txFsmState;

assign tx_TVALID = regslice_both_tx_V_data_V_U_vld_out;

assign tx_word_dest_V_fu_316_p1 = command_qpn_V[7:0];

assign zext_ln186_fu_362_p1 = p_Result_s_fu_351_p6;

assign zext_ln840_fu_391_p1 = i_1_loc_fu_110;

endmodule //cyt_rdma_cyt_rdma_tx
