name: Build and Test
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Get Build Dependencies
        id: get-build-dependencies
        uses: ./.github/actions/setup-accl-build-env

      - name: Build Emulator
        run: |
          cd ${{ github.workspace }}/test/model/emulator && cmake . && make -j2

      - name: Save Emulator
        id: cache-emulator-save
        uses: actions/cache/save@v3
        with:
          path: ${{ github.workspace }}/test/model/emulator/cclo_emu
          key: ${{ runner.os }}-emulator-${{ github.run_id }}

      - name: Build Test
        run: |
          source /opt/xilinx/xrt/setup.sh
          cd ${{ github.workspace }}/test/host/xrt && cmake . && make -j2

      - name: Save Emulator
        id: cache-test-save
        uses: actions/cache/save@v3
        with:
          path: ${{ github.workspace }}/test/host/xrt/bin/test
          key: ${{ runner.os }}-test-${{ github.run_id }}

  test_dma:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    needs: ["build"]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Get Run Dependencies
        id: get-run-dependencies
        uses: ./.github/actions/setup-accl-run-env          

      - name: Run Test
        run: |
          source /opt/xilinx/xrt/setup.sh
          ACCL_EMULATOR_PATH=./cclo_emu mpirun -np 1 --allow-run-as-root ./test --startemu --udp --gtest_filter=-*perf_counter*

  test_udp:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    needs: ["build"]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Get Run Dependencies
        id: get-run-dependencies
        uses: ./.github/actions/setup-accl-run-env          

      - name: Run Test
        run: |
          source /opt/xilinx/xrt/setup.sh
          ACCL_EMULATOR_PATH=./cclo_emu mpirun -np 2 --allow-run-as-root ./test --startemu --udp

  test_tcp:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    needs: ["build"]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Get Run Dependencies
        id: get-run-dependencies
        uses: ./.github/actions/setup-accl-run-env          

      - name: Run Test
        run: |
          source /opt/xilinx/xrt/setup.sh
          ACCL_EMULATOR_PATH=./cclo_emu mpirun -np 2 --allow-run-as-root ./test --startemu --tcp